---
title: "Chương 6: Một số quy trình chiết suất"
author: "TS. Hoàng Lê Sơn"
toc: true
bibliography: ../references/BookExtraction.bib
csl: ../references/natural-product-reports.csl
format: 
  html: 
    code-fold: true
    html-math-method: katex
  docx: default
---

## Tóm tắt 

## 6.1 Chiết suất catechin từ thực vật sử dụng màng

Mục tiêu của sáng chế này là phát triển một kỹ thuật dựa trên màng để
tinh chế và cô đặc các hóa chất flavonoid như flavon, flavanone,
flavanol, flavonol, isoflavone và flavon-3-ol từ các nguồn tự nhiên.
Trong vương quốc thực vật, flavonoid là chất chuyển hóa thứ cấp được tìm
thấy rất nhiều. Người ta đã chứng minh rằng flavonoid có đặc tính chống
oxy hóa và chống viêm cũng như kích thích hoạt động của enzyme giải độc
và ức chế hoạt hóa yếu tố phiên mã cũng như gây ra quá trình chết theo
chương trình trong chu kỳ tế bào, cũng như điều hòa sự xâm lấn của tế
bào và sự hình thành mạch và cản trở sự gắn kết với thụ thể. Các thành
phần flavonoid đã trở nên nổi bật trong kinh doanh dược phẩm dưới dạng
chất phụ gia do lợi ích y tế của chúng. Lá trà xanh, vỏ cam quýt, quả
mọng, bạch quả, rau mùi tây, đậu, trà, hắc mai biển và hành tây đều là
những nguồn flavonoid tuyệt vời. Lá tre, nho, táo và vô số nguồn tự
nhiên khác cũng chứa một lượng nhỏ chúng. Camellia sinensis được sử dụng
ở đây như một nguồn cho nghiên cứu thực nghiệm này. Hóa chất catechin đã
được chiết xuất bởi một số nghiên cứu. Quy trình xử lý các thành phần
kem trà có chứa trà đen trong nước nóng ngay lập tức và sau đó xử lý
phần chiết xuất cô đặc bằng catechin được bảo hộ bởi bằng sáng chế
US4680193A. EP1767097A2 là bằng sáng chế cho phương pháp chiết xuất
epigallocatechin gallate từ trà xanh. Chiết xuất trà được tạo ra bằng
cách đun nóng chiết xuất trà xanh từ 25 đến 60 C trước khi đưa nó qua
màng lọc nano. Catechin và polyphenol, hai hóa chất có hoạt tính sinh
lý, được chiết xuất bằng kỹ thuật được mô tả trong bằng sáng chế
WO1999008693. Các 254 Những tiến bộ trong chiết xuất và ứng dụng của hóa
chất thực vật có hoạt tính sinh học hợp chất chiết xuất sau đó được sử
dụng trong chế biến thực phẩm hoặc sản xuất dược phẩm. Quá trình chiết
xuất polyphenol từ lá C. Sinensis đã được thực hiện bằng phương pháp
chiết xuất có hỗ trợ vi sóng, mặc dù quy trình này không ảnh hưởng đến
chất lượng của sản phẩm được sản xuất. Cloroform, axeton, axetonitril và
etyl axetat đã được sử dụng trong một số nghiên cứu để chiết xuất
catechin từ lá của C. Sinensis, đây là chất rất không mong muốn. Một kỹ
thuật chiết xuất hai bước đối với phần tăng cường C. Sinensis EGC và
EGCG màu xanh lục cũng được mô tả. Catechin từ C. Sinensis có thể được
chiết xuất bằng lignocellulose làm chất hấp phụ; tuy nhiên, điều này chỉ
được báo cáo bởi một vài nghiên cứu. Việc chiết xuất catechin đã được
báo cáo là sử dụng nhiều phương pháp khác nhau. Tuy nhiên, những phương
pháp này không mang lại một quy trình khai thác hiệu quả. Cần phải nghĩ
ra một cách tiếp cận mới để vượt qua những trở ngại hiện đang cản trở
các thủ tục này. Hỗn hợp catechin cô đặc trong nước có thể được sản xuất
từ các nguồn thực vật và được sử dụng trong các chất bổ sung cấp dược
phẩm như được mô tả trong nghiên cứu này. Có một phương pháp chiết xuất
catechin không cần sử dụng dung môi hóa học và thay vào đó dựa vào nước.
Một số lợi ích, bao gồm giảm tiêu thụ năng lượng, kiểm soát chất lượng
sản phẩm bằng cách sử dụng màng phù hợp, tách ở nhiệt độ làm việc vừa
phải, v.v., làm cho quy trình này được khuyên dùng nhiều nhất. Sự đổi
mới này liên quan đến một phương pháp độc đáo và thân thiện với môi
trường để chiết xuất catechin từ các nguồn giàu catechin bằng công nghệ
màng. Quá trình này liên quan đến việc sử dụng các tế bào màng để xử lý
dòng chảy chéo hoặc hàng loạt và thu thập chất thấm giàu catechin của tế
bào màng cho các ứng dụng khác nhau \[15\].

## 6.2 Chiết gừng và ứng dụng

Zingiberaceae, bao gồm gừng, là những loại thảo mộc lâu năm với thân rễ
mập mạp, có mùi thơm và mùi thơm cay nồng. Gừng là một loại gia vị thiết
yếu, một phần quan trọng trong y học cổ truyền Trung Quốc và là một loại
cây đa năng có thể được sử dụng cho mục đích y học cũng như ẩm thực.
Theo các nghiên cứu, gừng có đặc tính chống oxy hóa, có thể loại bỏ các
gốc tự do và bảo vệ cơ thể con người khỏi bị tổn hại bởi các gốc tự do.
Sáng chế liên quan đến lĩnh vực y sinh học, và cụ thể hơn, nó liên quan
đến chất chiết xuất từ gừng, cũng như phương pháp điều chế và sử dụng
chất này trong y học. Thân rễ tươi của Rhizoma Zingiberis Recens
(Zingiber officinale) được sử dụng trong y học Trung Quốc để hỗ trợ tiêu
hóa và điều trị chứng khó chịu ở dạ dày, Bằng sáng chế về dược phẩm có
nguồn gốc tự nhiên 255 tiêu chảy, và khó chịu nói chung, trong số các
triệu chứng khác. Việc sử dụng Rhizoma Zingiberis Recens này đã được ghi
nhận từ năm 2000 và kể từ đó nó đã vượt qua các kỷ lục trước đó. Nghiên
cứu dược lý hiện đại của Rhizoma Zingiberis Recens cho thấy rằng nó có
đặc tính chống oxy hóa, kháng khuẩn, chống viêm, giảm cholesterol, chống
xơ vữa, tăng cường miễn dịch, chống nôn, chống dị ứng và chống nhiễm
trùng, cũng như hạ đường huyết và chống dị ứng, và có một chiết xuất
ethanol của Thân rễ Zingiberis Recens. Rhizoma Zingiberis Recens được sử
dụng trong điều trị đau thấp khớp, đau thắt lưng và đau xương, đau khớp
do ẩm ướt, viêm quanh khớp vai, sốt rét và lỵ trực khuẩn cấp tính, bệnh
thấp khớp, viêm khớp dạng thấp, gây tê vùng thắt lưng và gây tê ngoài
màng cứng. Rhizoma Zingiberis Recens đã được chứng minh là có các chức
năng như tăng chuyển hóa cơ thể con người, đặc tính chống viêm và giảm
đau, cũng như điều chỉnh chức năng của tuyến tiền liệt nam và điều trị
rối loạn tuyến tiền liệt và rào cản chức năng tình dục. Do đó, Rhizoma
Zingiberis Recens thường được sử dụng trong điều trị các vấn đề về sức
khỏe nam giới. Rhizoma Zingiberis Recens bao gồm nghiên cứu dược lý về
hệ thống sinh sản: dịch chiết nước của Rhizoma Zingiberis Recens đưa
tinh trùng chuột biến dạng thành cyclophosphamide để có tác dụng ức chế
đáng kể. Việc chiết xuất ethanol theo toa của Rhizoma Zingiberis Recens
và Rhizoma Curcumae Longue tương thích có thể làm giảm hiệu quả chất
lượng của tuyến tiền liệt chuột. Dịch chiết Rhizoma Zingiberis Recens
với liều lượng phù hợp có tính ổn định nhất định. Một trong những thách
thức trong lĩnh vực loại bỏ các gốc tự do là làm thế nào để tạo ra một
sản phẩm tự nhiên tinh khiết có khả năng loại bỏ các gốc tự do. Chiết
xuất gừng và kỹ thuật sản xuất cũng như cách sử dụng nó chủ yếu được đề
cập trong sáng chế này (Bằng sáng chế số: CN106924707B). Chiết xuất gừng
có thể được sử dụng để tạo ra chiết xuất gừng tự nhiên loại bỏ gốc tự
do. Sáng chế đề xuất một phương pháp điều chế chiết xuất gừng, bao gồm
làm khô Rhizoma Zingiberis Recens và nghiền thành lưới 70-90 để tạo ra
bột khô Rhizoma Zingiberis Recens để giải quyết các vấn đề kỹ thuật. Một
phương pháp khác bao gồm việc bổ sung xenlulaza đã nghiền, pectinaza và
cetyl trimetyl amoni bromua (CTAB) vào nước cất và trộn đều, trong đó tỷ
lệ chất lỏng của bột gừng khô với nước cất là 1 g:50e60 mL, và tỷ lệ
khối lượng bột gừng khô so với các chất đã nghiền là 1 g:6e10 mg. Phương
pháp này được thực hiện bằng cách đặt chất lỏng hỗn hợp vào nồi cách
thủy ở nhiệt độ 55--65 C trong 20--40 phút, khuấy và làm đông khô; thêm
ether dầu hỏa vào hỗn hợp; và sấy khô ở nhiệt độ thấp \[16\].

## 6.3 Chiết carotenoids từ nguồn thực vật

Sáng chế này phát triển một phương pháp chiết xuất caroten từ các loại
sinh khối khác nhau, bao gồm men Phaffia Rhodozyma. Việc chiết xuất
carotenoid từ các sinh khối này được thực hiện bằng cách đun nóng nguồn
caroten ở nhiệt độ cao với hỗn hợp dung môi bao gồm nước, dung môi
caroten kỵ nước như dầu thực vật và đồng dung môi hòa tan trong nước như
ethanol. Dễ dàng tích hợp vào chế độ ăn uống, cải thiện khả dụng sinh
học và ổn định chống lại quá trình oxy hóa chỉ là một số lợi thế. Năm
2004, Michael Kagan và Sergei Braun đã được trao bằng sáng chế này.
Phương pháp và thiết bị để chiết carotenoit từ sinh khối có trong tự
nhiên hoặc được trồng đặc biệt, như sinh khối giàu sắc tố carotenoit,
được bộc lộ ở đây. Có một số ứng dụng kinh tế cho các carotenoit này,
bao gồm sắc tố và chất chống oxy hóa cho cả người và động vật. Vì chúng
thường xuyên ăn vi giáp xác có chứa sắc tố đỏ astaxanthin nên cá hồi
nuôi trong tự nhiên có màu hồng. Astaxanthin được bổ sung nhân tạo được
sử dụng để mang lại màu hồng mong muốn cho thịt cá hồi khi chúng được
nuôi nhốt. Astaxanthin cần thiết với số lượng 60 mg mỗi kg thức ăn cho
cá để có được màu xanh lam này. Nó cũng được sử dụng để tăng cường màu
sắc của cá nuôi như cá tráp biển và tôm, cũng như trong nuôi trồng thủy
sản. Màu cá hồi đã đạt được bằng cách sử dụng cả astaxanthin tổng hợp và
tự nhiên. Để giảm chi phí, các công thức tổng hợp hầu hết đã thay thế
các nguồn tự nhiên. Sinh khối giàu astaxanthin như nấm men P. rhodozyma,
tảo Haematococcus pluvalis và các sản phẩm giáp xác đã được đưa trực
tiếp vào chế độ ăn của cá hồi trong các công thức có nguồn gốc tự nhiên.
Mặc dù astaxanthin có thể được kết hợp trực tiếp, nhưng nó không hiệu
quả về mặt chi phí so với sản phẩm tổng hợp vì hệ thống tiêu hóa của cá
không có khả năng chiết xuất astaxanthin từ các tế bào sinh khối; nói
cách khác, nguồn này có khả dụng sinh học kém đối với astaxanthin. Các
nguồn lycopene và carotene tự nhiên, hai loại carotenoid có ý nghĩa kinh
tế khác, hiện nay cũng đắt hơn so với các nguồn tổng hợp của chúng.
Astaxanthin và các carotenoid khác rất quan trọng về mặt kinh tế và một
số chiến lược đã 258 Những tiến bộ trong chiết xuất và ứng dụng của hóa
chất thực vật có hoạt tính sinh học đã được phát triển để tối ưu hóa
việc sản xuất sinh khối giàu caroten và cải thiện quá trình chiết xuất
caroten từ chúng. Sử dụng sáng chế hiện tại, một phương pháp chiết xuất
caroten từ nguồn caroten, bao gồm làm nóng nguồn caroten, hỗn hợp dung
môi đa pha bao gồm nước, dung môi caroten kỵ nước và đồng dung môi hòa
tan trong nước, được trình bày. Có thể nguồn caroten có chứa nước, dưới
dạng chất bổ sung hoặc thành phần tự nhiên. Hỗn hợp nhiều pha thường có
hai pha riêng biệt, một pha nước và pha còn lại không chứa nước hoặc
dầu; Tuy nhiên, đây không phải là luôn luôn như vậy. Trong quá trình xử
lý, sinh khối được khuấy trộn tốt nhất, ví dụ như xoáy. Quá trình chiết
được thực hiện trong khoảng thời gian ít nhất là 30 phút, nhưng tốt nhất
là từ 30 phút đến 3 giờ. Các dung môi kỵ nước, chẳng hạn như dầu ăn,
metyl axetat, etyl axetat, butyl axetat, ankan có số cacbon từ 5 trở lên
và chloroform, được ưu tiên sử dụng vì chúng kết hợp đặc tính kỵ nước
với khả năng dung môi chấp nhận được đối với sắc tố caroten. Carotenoid
tốt nhất được chọn để có ít nhất một số khả năng hạn chế để hòa tan dung
môi đồng, trong khi dung môi đồng khả năng chuyển carotenoid hòa tan
trong nó sang dung môi được xác định bởi hệ số của dung môi đồng phân
vùng. Rượu, ketone hoặc ether có thể được sử dụng làm đồng dung môi.
Este monoalkyl của ethylene glycol (Cellosolve) hoặc 1,3-dioxane hoặc
1,4-dioxane được ưu tiên làm đồng dung môi hòa tan trong nước, cũng như
metanol, etanol, n-propanol và iso-propanol. Dung dịch caroten trong dầu
ăn có thể được tạo ra trực tiếp bằng cách sử dụng dầu ăn làm dung môi;
tuy nhiên, trong một số trường hợp, sẽ có lợi khi sử dụng dung môi kỵ
nước và sau đó kết hợp dung môi kỵ nước với dầu ăn và làm bay hơi dầu từ
đó. Tốt hơn là, dung môi kỵ nước đã bay hơi trong quá trình chiết xuất
sẽ được sử dụng lại. Dung dịch caroten trong dầu ăn có thể được điều chế
bằng cách kết hợp dung dịch caroten trong dung môi không thể trộn lẫn
với nước với dầu và sau đó làm bay hơi dung môi khỏi hỗn hợp, theo một
khía cạnh khác của sáng chế này. Theo sáng chế, quá trình chiết xuất
carotenoid được thực hiện như mô tả trước đây để tạo ra dung dịch
caroten trong dầu ăn, sau đó được bổ sung vào các thành phần thức ăn
chăn nuôi để sản xuất nguyên liệu thức ăn chăn nuôi \[18\].

## 6.4 Thành phần hỗn hợp catechin flavonoids
