---
title: "Chương 5: Kỹ thuật làm khô dược liệu và cô đặc cao dược liệu"
author: "TS. Hoàng Lê Sơn"
toc: true
bibliography: ../references/BookExtraction.bib
csl: ../references/natural-product-reports.csl
format: 
  html: 
    code-fold: true
    html-math-method: katex
  docx: 
    reference-doc: custom-reference-doc.docx
  typst:
    papersize: a4
    margin:
      x: 2cm
      y: 2cm
    toc: true
    section-numbering: 1.1.a
    columns: 2
    fontsize: 11pt
---

::: {.right}
## Tóm tắt{.unnumbered .unlisted}
:::

Quá trình loại nước hoặc dung môi để thu được dược liệu khô hoặc cao khô là công đoạn quan trọng ảnh hưởng đến chất lượng các sản phẩm từ dược liệu. Với dược liệu tươi sau khi thu hái về, việc làm khô giúp ngăn chặn hư hỏng, biến màu, hoặc sụt giảm hoạt chất trước khi đem vào khâu chiết xuất do nhà máy chiết xuất thường cách xa khu nguyên liệu. Bên cạnh đó, dược liệu khô có thể là sản phẩm cuối đến tay người tiêu dùng, việc làm khô đúng cách giúp giữ được chất lượng dược liệu cũng có thể ảnh hưởng đến mùi vị và thị giác giúp thu hút người sử dụng. Trừ nhóm tinh dầu dễ bay hơi, các cao chiết thu được sẽ cần loại dung môi thu cao đặc hoặc cao khô. Quá trình này cần tác động nhiệt dẫn tới thay đổi chất lượng cao dược liệu. Chương này sẽ đề cập tới chất lượng dược liệu gồm màu sắc và mùi vị với các kỹ thuật tiền xử lý như chần, siêu âm, xung điện và giảm kích thước dược liệu cũng như các phương pháp sấy dược liệu như sấy dưới ánh sáng mặt trời, sấy lạnh, sấy tầng sôi, sấy bằng tia hồng ngoại. Phần tiếp theo của chương là vai trò chuẩn hóa cao dược liệu và các phương pháp sấy như sấy tầng sôi, đông khô. 



## 5.1 Cải thiện chất lượng dược liệu với kỹ thuật sấy

### 5.1.1 Yêu cầu về chất lượng dược liệu

Dược liệu sấy khô thường có gì cao dẫn tới kỳ vọng về chất lượng sẽ cao hơn. [@schaarschmidt_public_2016] Các yêu cầu chất lượng của dược liệu khô để đảm bảo an toàn về mặt hóa học và vi sinh như độ ẩm, tạp chất, dư lượng chất bảo vệ thực vật, aflatoxin và kim loại nặng. Các chỉ tiêu này đòi hỏi trang thiết bị hiện đại để kiểm tra. Tuy nhiên, đặc trưng ban đầu về màu sắc và mùi thơm được người mua quan tâm nhất. [@schaarschmidt_public_2016] Phần dưới đây đề cập tới tiêu chuẩn màu sắc và mùi hương của dược liệu.


**Mùi hương và Tinh dầu**

Mùi của dược liệu do nhiều yếu tố quyết định trong đó thành phần tinh dầu thu được từ cất keo hơi nước được coi sẽ quyết định tới đặc trưng của dược liệu. Ở dược liệu tươi, tinh dầu được tồn trữ trên bề mặt lá, trong bộ phận riêng biệt gọi là trichome, được cấu tạo là một đơn bào hoặc đa bào tại lớp biểu bì. [@werker_trichome_2000] Sau khi sấy khô, tinh dầu được giữa lại phụ thuộc vào tính nguyên vẹn của bộ phận tồn trữ. Hệ quả là cải thiện hương thơm của thảo mộc khô phụ thuộc vào công nghệ bảo tồn tính toàn vẹn hoặc giảm thiểu tổn hại của trichome. Thêm nữa, các tinh dầu cũng có thể tồn tại trong liên kết glycoside, hòa tan trong nước và có thể tích lũy trong mô thực vật. [@winterhalter_glycoconjugated_1997]

**Thành phần tinh dầu và sự thay đổi**

Tinh dầu là một hỗn hợp chứa một vài hay nhiều hoạt chất, một số tinh dầu có thể chứa hơn một trăm thành phần hóa học. [@antal_effect_2011] Thành phần hóa học trong tinh dầu phụ thuộc vào loại thảo mộc, mùa thu hạch, chế biến, độ tuổi thảo mộc và điều kiện bảo quản. [@dokhani_analysis_2005] Mỗi hợp chất sẽ đóng góp vào tạo thành mùi hương cho tinh dầu. Sự đóng góp này phụ thuộc vào ngưỡng tạo mùi của chúng và có thể xác định dựa trên cấu trúc hóa học và khả năng bay hơi. [@turek_stability_2013] Những thay đổi nhỏ về nồng độ (do phản ứng hóa học hay phân hủy)- ngay cả với thành phần nhỏ- có thể dẫn tới thay đổi mạnh mẽ về hương vị của tinh dầu. [@grosch_evaluation_2001] Tinh dầu có thể được chia thành 2 phần: (1) Phần dễ bay hơi chiếm khoảng 90-95% tổng lượng tinh dầu bao gồm các monoterpen, sesquiterpen, aldehyde, rượu và este; và (2) Phần không bay hơi gồm hydrocarbon, sterol và các phân tử có trọng lượng phân tử lớn khác như triterpen, squalene và saponin. [@crozier_plant_2006; @orphanides_drying_2016] Một số hợp chất hóa học chính của tinh dầu thảo dược đã được báo cáo, chẳng hạn như 1,8-cineole trong lá nguyệt quế , p-mentha-1,3,8-triene, $\beta-phellandrene$, và isopropenyl 4-methylbenzene trong mùi tây [@diaz-maroto_effect_2002] ; $\alpha-pinene$, camphene, 1,8-cineole, camphor, bornyl axetat và borneol trong cây hương thảo [@rao_rosemary_1998] ; và $\alpha-pinene$, $\beta-pinene$, 1,8-cineole, camphor, camphene, a-terpineol, caryophyllene, ascaridole và bornyl acetate ở các loài achillea của Iran. [@dokhani_analysis_2005] 

Nhiều nghiên cứu được thực hiện để xác định thành phần hóa học của tinh dầu. Tuy nhiên, phương pháp chiết xuất và phân tích có thể ảnh hưởng đến kết quả. [@dokhani_analysis_2005] Thành phần hóa học của tinh dầu là những chất không ổn định. Chúng có thể dễ dàng chuyển đổi thành các loại hợp chất khác thông qua các phản ứng hóa học như phản ứng oxy hóa, đồng phân hóa, đóng vòng hoặc khử hydro. Những phản ứng hóa học này cũng có thể được kích hoạt bằng enzyme. [@turek_stability_2013] Một trong những thay đổi thành phần hóa học quan trọng nhất là quá trình oxy hóa. Phản ứng oxy hóa dẫn tới ảnh hưởng đến quá trình phân hủy terpenoid, đây là nhóm hợp chất quan trọng nhất trong tinh dầu. [@baser_essential_2011] Quá trình oxy hóa diễn ra, các sản phẩm thứ cấp xuất hiện như các gốc tự do hydroperoxide, đây cũng là nhóm chất thúc đẩy quá trình oxy hóa diễn ra mạnh hơn khi có thêm tác động bởi ánh sáng, nhiệt độ và acid. [@turek_stability_2013] 

Nhiệt độ trong quá trình sấy khô hoặc bảo quản có thể ảnh hưởng đến chất lượng tinh dầu. [@lee_temperature_2007; @choe_mechanisms_2006] Thêm nữa, nhiệt độ có thể làm cho sụt giảm hàm lượng tinh dầu có trong dược liệu khô. Chúng có thể dễ dàng chuyển đổi thành các loại hợp chất khác thông qua các phản ứng hóa học như phản ứng oxy hóa, đồng phân hóa, đóng vòng hoặc khử hydro. Những phản ứng hóa học này cũng có thể được kích hoạt bằng enzyme. [@turek_stability_2013] Một trong những thay đổi thành phần hóa học quan trọng nhất là quá trình oxy hóa. Phản ứng oxy hóa dẫn tới ảnh hưởng đến quá trình phân hủy terpenoid, đây là nhóm hợp chất quan trọng nhất trong tinh dầu. [@baser_essential_2011] Quá trình oxy hóa diễn ra, các sản phẩm thứ cấp xuất hiện như các gốc tự do hydroperoxide, đây cũng là nhóm chất thúc đẩy quá trình oxy hóa diễn ra mạnh hơn khi có thêm tác động bởi ánh sáng, nhiệt độ và acid. [@turek_stability_2013] Do đó, nhiệt độ trong quá trình sấy khô hoặc bảo quản có thể ảnh hưởng đến chất lượng tinh dầu. [@lee_temperature_2007; @choe_mechanisms_2006] Thêm nữa, nhiệt độ có thể làm cho sụt giảm hàm lượng tinh dầu có trong dược liệu khô. 

Sự hiện diện của ánh sáng là một yếu tố quan trọng khác ảnh hưởng đến sự phân hủy của tinh dầu, đặc biệt là trong sử dụng phương pháp phơi nắng. Khi đó, các loại thảo dược tiếp xúc trực tiếp với ánh sáng mặt trời, hoặc trong quá trình bảo quản các loại thảo mộc dược khô không đựng trong bao bì tránh ánh sáng. Sự hiện diện của ánh sáng, dù là tia cực tím hay ánh sáng nhìn thấy, đều đẩy nhanh quá trình tự oxy hóa bằng cách kích hoạt quá trình tách hydro, dẫn đến sự hình thành các gốc alkyl lipid. [@choe_mechanisms_2006] Hai loại phân tử oxy chịu trách nhiệm cho quá trình tự oxy hóa các chất thân dầu: Oxy nhóm đơn (1O2) và Oxy bộ ba (3O2). Trong khi oxy 1O2 được cho là chủ yếu tham gia vào giai đoạn đầu của quá trình oxy hóa dầu, [@lee_quenching_1988] oxy 3O2 có khả năng phản ứng với các gốc alkyl ở áp suất oxy bình thường và tạo thành các gốc peroxyl lipid. Các gốc peroxyl lipid này có khả năng hấp thụ hydro từ các phân tử khác và thúc đẩy quá trình oxy hóa, dẫn đến sự phân hủy của các hợp chất thơm. Ngoài ra, những yếu tố khác ảnh hưởng đến sự hình thành và phân hủy tạo gốc hydroperoxide như sự hiện diện của oxy, chất chống oxy hóa, hàm lượng nước, hiện diện của kim loại nặng và cấu trúc hóa học của các hợp chất. [@turek_stability_2013] 

Sấy khô làm giảm đáng kể lượng tinh dầu trong nhiều loại thảo mộc như 36-45% ở húng quế, 23-33% ở kinh giới và 6-17% ở oregano ngay cả khi các loại thảo mộc được sấy khô trong bóng râm. [@nykanen_effect_1987; @diaz-maroto_effect_2002] Trong quá trình sấy khô, thành phần dễ bay hơi của tinh dầu có thể thay đổi do sự hình thành của các hợp chất thơm thứ cấp như rượu, aldehyd, peroxid và keton. [@turek_stability_2013] Các sản phẩm thứ cấp này có thể chiếm tỷ lệ phần trăm cao trong tổng hàm lượng chất dễ bay hơi của thảo dược khô. [@huopalahti_effect_1985] Trong thì là khô được sấy bằng phương pháp sấy khí nóng ở nhiệt độ 25, 40 và 50 $^oC$ thì hàm lượng các chất thơm thứ cấp có thể cao tới 50%. Sự thay đổi này có thể do sự phá vỡ tế bào, giải phóng các hợp chất, phản ứng oxy hóa diễn ra hoặc quá trình thủy phân hợp chất dễ bay hơi đang ở dạng glycoside. [@xing_effects_2017] Việc giảm hoặc thay đổi các hợp chất dễ bay hơi trong thảo mộc khô trong quá trình sấy phụ thuộc vào các thông số sấy bao gồm phương pháp sấy, nhiệt độ, mức độ chân không (trong trường hợp sử dụng phương pháp sấy chân không hoặc sấy lạnh), thời gian sấy và lượng nước bay hơi trong quá trình sấy. [@antal_effect_2011; @figiel_overall_2016] Việc sấy khô các loại thảo mộc có thể làm giảm các hợp chất dễ bay hơi tuy nhiên lại cho phép bảo quản các hợp chất dễ bay hơi tốt hơn các phương pháp khác. [@chua_influence_2019] Nhiệt độ sấy đóng vai trò quan trọng trong việc bảo quản các hợp chất dễ bay hơi của dược liệu khô sau quá trình sấy. Áp dụng nhiệt độ sấy cao thường dẫn đến thất thoát hàm lượng các hợp chất dễ bay hơi. Ở nhiệt độ sấy cao, tế bào trichomes có thể có nguy cơ bị vỡ dẫn đến mất các hợp chất dễ bay hơi. Ngoài ra, nhiệt độ sấy khô cao có thể thúc đẩy quá trình phân hủy các hợp chất không bền với nhiệt trong tinh dầu. [@argyropoulos_changes_2014] Tuy nhiên, một số kết quả mâu thuẫn đã được quan sát thấy. Trong trường hợp lá sim sấy khô bằng không khí nóng, nhiệt độ sấy $50^oC$ cho hàm lượng citral cao hơn so với sấy ở nhiệt độ 30 và $40^oC$. Hiệu quả bảo quản tốt hơn này có thể là do lớp vỏ được hình thành trên lá sim. Bề mặt lá hạn chế sự khuếch tán của các hợp chất dễ bay hơi. [@buchaillot_drying_2009] 


Duy trì mức chân không là một trong những yếu tố quan trọng nhất ảnh hưởng đến hàm lượng tinh dầu. [@chua_influence_2019] Trong trường hợp bạc hà đông khô, mặc dù việc giảm áp suất buồng dẫn đến giảm thời gian sấy, nhưng cũng gây ra sự thất thoát đáng kể các hợp chất dễ bay hơi. [@antal_effect_2011] Trong trường hợp sấy chân không bằng vi sóng, việc tăng mức chân không làm giảm chất lượng của các hợp chất dễ bay hơi của hương thảo khô. [@calin-sanchez_volatile_2012] 

Ảnh hưởng của các phương pháp làm khô này đến chất lượng của các loại thảo mộc khô được xem xét trong phương pháp "Sấy lạnh" và "Sấy chân không bằng vi sóng". Lượng ẩm bốc hơi từ các mô là một yếu tố khác ảnh hưởng đến các hợp chất dễ bay hơi trong các loại thảo dược khô. Oregano sấy khô trong không khí, lượng nước bay hơi có tương quan chặt chẽ với việc giảm các hợp chất dễ bay hơi, vì trong quá trình sấy khô, hơi nước có thể đóng vai trò là chất mang cho phép khuếch tán các hợp chất dễ bay hơi từ các mô ra môi trường xung quanh. [@fennell_assessing_2004] Ngoài ra, các hợp chất dễ bay hơi có ái lực với nước cao có nhiều khả năng bị mất đi trong quá trình sấy khô. [@sellami_qualitative_2011] 

Sự thay đổi của các hợp chất dễ bay hơi trong quá trình sấy khô cũng phụ thuộc vào một số yếu tố của thảo dược bao gồm độ ẩm ban đầu, tuổi thu hoạch, điều kiện sinh trưởng và thời gian thu hoạch. [@ascrizzi_photochemical_2018] Điều kiện bảo quản cũng ảnh hưởng đến hàm lượng chất dễ bay hơi của sản phẩm sấy khô, đặc biệt là khi có ánh sáng và oxy. [@baritaux_effects_1992] 

Việc giảm một số thành phần tinh dầu có thể được coi là một lợi ích, chẳng hạn như giảm pulegone - một chất độc gan xuất hiện trong *Hedeoma pulegioides*, *Mentha pulegium* và *Mentha longifolia* L. subsp. capensis. [@asekun_effects_2007; @chen_application_1998] Hoạt chất này đã giảm đáng kể khi sấy khô bằng không khí nóng ở $40^oC$. Do đó, người ta cho rằng các loài trên nên được tiêu thụ ở dạng khô thay vì ở dạng tươi. 

**Màu sắc** 

Mục tiêu chính của nhiều nghiên cứu làm khô thảo mộc là cải thiện màu sắc của sản phẩm sấy khô hoặc giảm sự thay đổi màu sắc trong quá trình sấy khô và bảo quản. [@baritaux_effects_1992] Màu sắc xấu đi trong các loại thảo mộc khô được kích hoạt bởi sự suy giảm của các sắc tố như chất diệp lục và anthocyanin. Đối với các loại thảo dược xanh, chất diệp lục bị phân hủy là sự thay đổi phổ biến nhất có thể xảy ra trong quá trình sấy khô. [@rayaguru_effect_2010] Lafeuille *et al.* năm 2014 đã phân tích chất diệp lục và các chất dẫn xuất màu trong các loại thảo dược chịu ảnh hưởng của các quá trình sấy khô khác nhau. [@lafeuille_quantitation_2014] Trong bài báo này, một thang đo chất diệp lục bị phân hủy được thiết kế để đánh giá màu sắc của các loại thảo dược khô. Thang được chia thành bốn loại theo lượng sắc tố xanh giữ lại được sau quá trình sấy khô: (1) không có tác động đáng kể (>90% được giữ lại), (2) tác động thấp (65--90% được giữ lại), (3) tác động trung bình (35--65% được giữ lại) và (4) tác động quan trọng (<35% được giữ lại). Theo các tiêu chí này, đông khô có thể được phân loại vào thang đầu tiên vì không có tác động đáng kể đến hàm lượng của nhóm chất diệp lục tạo màu xanh lá cây. Phương pháp sấy khô phổ biến nhất, sấy khô bằng khí nóng, được xếp vào bậc thang thứ hai. Phơi nắng được xếp vào loại thứ tư do tác động đáng kể đối với việc giữ màu. 

Nhiệt tác động tới chất diệp lục cũng đã được nghiên cứu. [@di_cesare_changes_2003] Hai loại chất diệp lục chính chịu trách nhiệm cho sự thay đổi màu sắc của thảo dược trong quá trình sấy khô: chất diệp lục a và b. Cấu trúc hóa học của hai chất diệp lục rất giống nhau, với sự khác biệt duy nhất khi chất diệp lục b có một nhóm aldehyde ở vị trí C7 của vòng porphyrin. Màu của chất diệp lục a là màu xanh lam, trong khi chất diệp lục b có màu vàng lục. Do có carbon bất đối ở C13, chất diệp lục a và b có thể chuyển thành đồng phân của chúng. Các đồng phân này có quang phổ khả kiến gần không thay đổi và không ảnh hưởng đến màu sắc của sản phẩm sấy khô. Sự thay đổi các nhóm thế chất diệp lục có thể thấy được trên quang phổ. Những thay đổi phổ biến nhất trong nhóm này là sự mất nhóm phytol ở C17 do phản ứng thủy phân được xúc tác bởi các enzym trong thực vật như chlorophyllase. [@lafeuille_quantitation_2014] Chlorophyllide là một dẫn xuất từ sự mất phytol từ phân tử chất diệp lục có quang phổ nhìn thấy giống như chất diệp lục, tuy nhiên, độ hòa tan trong nước cao hơn và có thể bị mất dễ dàng trong các quá trình tiền xủ lý như chần. Đây cũng là một trong những quá trình phổ biến nhất. Kim loại Mg2+ tạo phức chelate mất đi sẽ tạo màu nâu ôliu. Các bước xử lý làm hỏng màng tế bào, chẳng hạn như cắt để thu hoạch, đun nóng hoặc sấy khô có thể giải phóng các chất có tính acid trong nhựa cây phản ứng với các chất diệp lục và thúc đẩy sự mất mát của Mg2+. Chelate Mg2+ có thể bị mất bởi cả nhiệt khô và ẩm và cũng xảy ra với các điều kiện acid bên ngoài tác động. [@aronoff_chemistry_1960] Mg2+ chelate hóa bị mất là một trong những hiện tượng xuống cấp phổ biến nhất về màu sắc của thảo mộc trong quá trình sấy khô. Ngoài ra, chlorophyllide nhạy cảm với nhiệt hơn chlorophyll về mặt mất Mg2+, sự mất mát của Mg2+ từ các phân tử chlorophyllide tạo ra pheophorbide màu nâu ô liu. Sự mất nhóm phytol từ cấu trúc diệp lục do nhiệt xảy ra dễ dàng hơn sự mất mát của Mg2+. [@di_cesare_changes_2003; @orlien_biochemical_2019] Vì chất diệp lục a nhạy cảm với nhiệt hơn chất diệp lục b, sự phân hủy chất diệp lục a dẫn đến sự thay đổi tỷ lệ chất diệp lục a/b, làm thay đổi màu sắc của sản phẩm sấy khô từ xanh lá cây sang xanh lục vàng. Mô thực vật bị sụp đổ trong quá trình làm khô có thể dẫn đến việc giải phóng các phân tử chất diệp lục khỏi phức hợp protein, điều này có thể thúc đẩy quá trình chuyển đổi chất diệp lục thành pheophytin do cấu trúc của chất diệp lục tiếp xúc nhiều hơn với nhiệt. Sự kiện này cũng có thể dẫn đến việc giải phóng các chất nền cho các phản ứng hóa nâu do enzyme ra các khu vực xung quanh. Sự thoái hóa của chất diệp lục a và b cũng phụ thuộc vào loại thực vật. Người ta đã chứng minh rằng mùi tây và mùi tây khô, là những loại thảo mộc thuộc họ Apiaceae, cho thấy khả năng giữ lại chất diệp lục a và b cao hơn so với húng quế, bạc hà và oregano, là những loại thảo mộc thuộc họ Lamiaceae. [@sledz_influence_2012] Có thể giảm sự thay đổi về màu sắc bằng cách tối ưu hóa các thông số của quá trình sấy như nhiệt độ sấy, thời gian và tốc độ không khí. Các biện pháp tiền xử lý trước khi sấy khô, chẳng hạn như chần [@di_cesare_changes_2003] và điện trường xung [@kwao_effect_2016], đã được báo cáo là cải thiện màu sắc của các loại thảo dược khô.

### 5.1.2 Tiền xử lý trước khi sấy khô dược liệu

Tiền xử lý trước khi sấy khô dược liệu là công đoạn nhằm đạt được loại thảo mộc khô chất lượng cao, rút ngắn thời gian sấy khô và giảm tiêu thụ năng lượng. [@deng_chemical_2019] Công đoạn này làm tốt giúp ích cho giảm chi phí trực tiếp trong quy trình sấy khô. Một số phương pháp tiền xử lý được đề cập tới như phương pháp chần, dùng xung điện trường hay siêu âm.


**Chần dược liệu**

Chần mang lại lợi ích cho việc làm khô nhiều loại thảo mộc tươi đặc biệt là giảm sự thay đổi mày sắc. Chần bằng hơi nước trong 15 giây giúp tắc tốc độ làm khô lá húng quế lên 10 lần so với loại không xử lý. [@rocha_effect_1993] Lá húng quế chần giữa sắc tốt hơn khi tăng tỷ lệ Chlorophyll a và b. Kết quả cũng đúng với lá mùi tây khi tốc độ sấy nhan hơn 30% và mức năng lượng sử dụng giảm 73%. Ngoài ra hàm lượng lutein cao hơn và màu sắc đẹp hơn. [@sledz_impact_2016] Với lá thì là khi chần nước nóng trong 1 phút trước khi sấy bằng các phương pháp gồm sấy như sấy chân không ($45^oC$), sấy hồi lưu ($45^oC$) và đông khô, cho thấy chần giúp giảm thời gian sấy. [@raghavan_studies_1994] Tuy nhiên điều này có thể mất lượng tinh dầu nhiều hơn. Kết quả ngược lại khi quan sát với chần rau mùi tại $80^oC$ trong nước. Thêm một lượng muối khi chần có thể đem lại một số lợi ích nhất định. Thêm kali metabisulfite vào dung dịch chần đã cải thiện khả năng giữ lại acid ascorbic, $\beta-caroten$ và chất diệp lục của lá rau dền và cỏ cà ri khô. [@negi_effect_2000] Về kỹ thuật, chần thảo mộc hiện tại có một số phương pháp như chần nước, chần bằng hơi nước và chần bằng vi sóng. [@singh_processing_1996] Kinh giới và hương thảo chần bằng các kỹ thuật trên trước khi sấy khô cho màu sắc tốt hơn. Ngoài ra phương pháp chần nước cho giữ màu tốt nhất tiếp theo là sử dụng hơi nước và vi sóng. Tuy nhiên, chần bằng vi sóng cho thấy hàm lượng acid ascorbic cao hơn và kết cấu tốt hơn. Phương pháp chần bằng chân không cũng có thể được áp dụng. Thảo mộc đóng gói trong túi chân không sau đó chần trong nước nóng giữ lại tốt các hợp chất có hoạt tính sinh học trong sản phẩm sấy khô. Ví dụ như chè java chần chân không ở nhiệt độ $100^oC$ sau đó sấy đối lưu, sấy hút ẩm, sấy năng lượng mặt trời và sấy thăng hóa cho thấy hàm lượng sinensetin và eupatorin cao hơn trong sản phẩm sấy khô so với phương pháp chần nước. [@klungboonkrong_drying_2018] Ngoài ra, chần chân không giúp sản phẩm đẹp hơn do tế bào không bị tổn thương như các mẫu chần khác. Chần cũng có thể gặp một số vấn đề liên quan đến chất lượng thảo mộc. Phương pháp này có thể làm giảm đáng kể hoạt tính chống oxy hóa của một số thảo mộc như *Basella alba, Corchorus olitorius* và *Solanum macrocarpon*. [@oboh_effect_2005] Quá tình này cũng có thể làm giảm mùi thơm của một số loài rau thơm do quan sát thấy sự phá hủy các tuyến dầu. Chần làm mất nhiều hợp chất thơm trong mẫu sấy khô.

**Xung điện trường- Pulsed electric field (PEF)**

Xung điện trường là phương pháp xử lý không dùng nhiệt, áp dụng điện trường bên ngoài để tác động tới tế bào và mô khi gây các lỗ thủng trên màng tế bào. Một số nghiên cứu đã đánh giá tác dụng của PEF tới làm khô dược liệu. Hầu hết các nghiên cứu này tập trung vào khía cạnh tạo tổn thương vĩnh viễn tế bào tăng quá trình khuếch tán độ ẩm và giảm đáng kể thời sấy. Việc giảm này giúp đem lại lợi thế đặc biệt với thảo mộc không bền với nhiệt. [@orphanides_effect_2013] Mặc dù vậy, phương pháp này cũng có thể tác động thuận nghịch (tế bào không bị phá hủy khi áp dụng PEF) và đã có nghiên cứu của Telfser và Galindo năm 2019 để tiền xử lý trước khi sấy khô. [@telfser_effect_2019] Xung điện trường làm mở khí khổng trong suốt quá trình sấy khô bằng khi nóng, tăng tốc độ sấy và cải thiện màu sắc, mùi vị của sản phẩm cuối. Trên húng quế, thời gian sấy giảm với 57% trong sấy khí nóng, 33% trong sấy chân không và 25% với đông khô. Tế bào trichome được bảo vệ tốt hơn trong sấy khi nóng và chân không. Tuy nhiên, tế bào trichome bị hư hỏng ở các lá đông khô qua xử lý lẫn không qua xử lý. 

**Siêu âm - Ultrasound**

Siêu âm là phương pháp tiền xử lý không dùng nhiệt để làm khô nguyên liệu. Quá trình này sử dụng sóng siêu âm có công suất thấp (20--100kHz) và cường độ cao (10--1000 W/cm) vào trong nguyên liệu, sóng dẫn truyền trong dược liệu mà không gia nhiệt hoặc gia nhiệt nhẹ. Kết quả sóng tạo ra các lỗ siêu nhỏ trên bề mặt, giảm hiệu ứng cứng bề mặt nguyên liệu- nguyên nhân ngăn nước thoát ra, dẫn tới cải thiện thời gian sấy. [@cullen_novel_2012] Sử dụng siêu âm tiền xử lý đã được báo cáo với nhiều dược liệu. Ví dụ mùi tây cho thấy xử lý bằng siêu âm cho tổng hàm lượng phenolic, chất diệp lục và lutein cao hơn khi lá không được xử lý. [@dadan_selected_2018] Thời gian sấy giảm 30% khi chọn xử lý siêu âm với cỏ xạ hương. Tuy nhiên, tác động chỉ thấy ở nhiệt độ sấy dưới $70^oC$. [@rodriguez_influence_2014]

**Giảm kích thước dược liệu**

Giảm kích thước dược liệu khô trước khi chiết xuất là cần thiết trước khi chiết nhóm hoạt chất mong muốn. Khi tiến hành giảm kích thước với dược liệu tươi, quá trình này cần diễn ra càng sớm cáng tốt để giảm nguy cơ suy giảm chất lượng do enzyme hoặc nhiễm tạp vi sinh vật. Việc nghiền nguyên liệu thành các hạt nhỏ gây ra vỡ mô và tế bào làm tăng hiệu quả chiết xuất do tăng diện tích tiếp xúc. Một số thiết bị để giảm kích thước dược liệu như máy nghiền dao (lá và hoa, thân, vỏ cây và rễ), máy nghiền bi (các nguyên liệu cứng, giòn và dễ vỡ), máy nghiền búa (nghiền thô lá, vỏ cây và rễ, vật liệu dễ vỡ và nhựa) và máy nghiền đĩa (đối với chiết xuất khô, quả và hạt hút ẩm, vật liệu cứng, giòn và dễ vỡ tạo ra một loại bột rất mịn). [@world_health_organization_who_2007]

### 5.1.3 Phương pháp làm khô dược liệu

Phương pháp làm khô là một trong những yếu tố chính ảnh hưởng đến chất lượng thảo mộc khô. Các phương pháp sấy áp dụng nhiệt độ cao sẽ làm giảm đáng kể chất thơm vì chúng nhạy cảm với nhiệt và dễ dàng bay hơi khỏi mô trong quá trình sấy. [@khangholi_effect_2008] Tuy nhiên, hàm lượng tinh dầu trong một số loài thảo mộc không bị ảnh hưởng bởi phương pháp sấy như lá nguyệt quế khi sấy đối lưu tại 40, 50, 60 $^oC$, phơi nắng hay sấy trong bóng râm. [@demir_mathematical_2004] Các phương pháp sấy thảo dược phổ biến như phơi nắng, sấy trong bóng râm, sấy thăng hoa và sấy bằng không khí nóng. Trong đó sấy bằng không khi nóng tại nhiệt độ 40-60 $^oC$ là phổ biến nhất dung trong nghiên cứu ở quy mô phòng thí nghiệm. [@shaw_drying_2007]  Do tác động không mong muốn của nhiệt độ sấy tới chất lượng của dược liệu khô, nhiều phương pháp đã được phát triển để thay thế như sấy khô bằng năng lượng mặt trời, sấy khô bằng vi sóng, sấy chân không bằng vi sóng, sấy bằng tia hồng ngoài, sấy bằng bơm nhiệt và sấy khô tiếp xúc. Ảnh hưởng của từng phương pháp đến chất lượng của dược liệu khô được bàn luận ở phần tiếp theo.

**Sử dụng ánh nắng mặt trời**

Phơi nắng được coi là phương pháp sấy thảo mộc lâu đời nhất và vẫn được sử dụng cho tới ngày nay. Phương pháp này phổ biến tại các quốc gia cận nhiệt đới và nhiệt đới. Quá trình này diễn ra khi thảo mộc tươi đặt trên giá phơi thông gió tốt đặt trực tiếp dưới ánh năng mặt trời. [@janjai_solar_2012]  Phương pháp này không phù hợp cho một số thảo mộc do màu sắc và mùi thơm bị thay đổi quá nhiều. Đối với hoa cúc la mã, lượng các thành phần chính như isobutyl isobutyrat, 3-metylbutyl isobutyrat và propyl tiglate trong dược liệu phơi nắng thấp hơn so với mẫu sấy khô bằng không khí nóng ở $40^oC$. [@omidbaigi_effect_2007] Cỏ chanh phơi khô dưới ánh nắng mặt trời có chứa lượng tinh dầu tổng số thấp hơn so với cỏ chanh khô thu được từ quá trình sấy khô bằng không khí nóng. [@mohamed_hanaa_lemongrass_2012] Ở húng quế (*Ocimum basilicum* L.), phơi nắng làm giảm hàm lượng tinh dầu nhiều hơn so với phơi trong bóng râm và sấy bằng không khí nóng ở $40^oC$. Phơi nắng cũng gây ra thiệt hại nhiều hơn cho bề mặt biểu bì, làm co lại tế bào trichome và giảm hàm lượng hoạt chất trong lá *Vernonia amygdalina* nhiều hơn so với phơi trong bóng râm. [@alara_mathematical_2018]

**Sấy trong bóng râm**

Sấy trong bóng râm là một phương pháp dùng năng lượng mặt trời tạo nguồn nhiệt. Quá trình giống phơi nắng nhưng thảo mộc được đặt trong bóng râm có thông gió tốt với độ ẩm thấp và đặc biệt thảo mộc không tiếp xúc trực tiếp với ánh sáng mặt trời. [@sharma_solar-energy_2009] Phương pháp này đem lại lợi thế hơn so với phơi nắng chính là giảm thiểu tác động của các phản ứng hóa học do ánh sáng tác động như quá trình oxy hoa. Thời gian diễn ra dài hơn so với phơi năng và thường được xem là quá dài. Về chất lượng, thảo dược lựa chọn theo phương pháp này có ưu điểm tốt hơn về hàm lượng tinh dầu và màu sắc tươi hơn so với các phương pháp sấy khác như sấy khí nóng, phơi nắng, sấy vi sóng và đông khô. [@omidbaigi_effect_2007] Ngoài ra, phương pháp sấy trong bóng râm giúp bảo vệ tế bào trichome tốt hơn. Kết quả này được công bố trong nghiên cứu so sánh phương pháp sấy là loài *Lippia Citriodora* gồm sấy trong bóng râm, sấy khô tại nhiệt độ 60$^oC$ và sấy chân không 40$^oC$. [@ebadi_influence_2015] Sấy trong bóng râm cũng cho thấy khả năng giữ lại các hợp chất có hoạt tính tốt hơn ví dụ như loài *Orthosiphon aristatus*. [@abdullah_effect_2012] Tổng hàm lượng phenolic cao nhất khi sấy trong bóng râm nếu so với sấy khô tại nhiệt độ $40^oC$. Ngoài ra, hàm lượng acid rosmarinic vẫn có thể duy trì hàm lượng gần bằng dược liệu tươi. Tuy nhiên, một số đặc trưng của thảo mộc có thể mất đi ví dụ khả năng chống oxy hóa của bạc hà và tía tô giảm đáng kể khi sấy trong bóng râm trong 10 ngày tại nhiệt độ dao động từ 25-32$^oC$. Ngay cả acid ascorbic và các carotenoid cũng giảm. [@capecka_antioxidant_2005] Sự suy giảm tinh dầu lẫn hàm lượng một số thành phần có hoạt tính vẫn không thể bỏ qua lợi thế của phương pháp này như chi phí đầu tư thấp, sản phẩm vẫn ở mức chấp nhận được. [@janjai_solar_2012]

**Sấy bằng năng lượng mặt trời**

*Thuật ngữ tiếng Anh:* Solar-assisted drying

Phương pháp này được phát triển từ phơi nắng. Năng lượng mặt trời dồi dào và miễn phí do đó phương pháp này thu hút được quan tâm của nhiều nhà nghiên cứu. Mục đích phương pháp này sử dụng năng lượng hiệu quả và khắc phục phương pháp phơi nắng truyền thống. Sấy bằng năng lượng mặt trời có thể chia làm 3 nhóm gồm (1) Sấy trực tiếp bằng ánh sáng mặt trời, (2) Sấy bằng mặt trời gián tiếp hoặc Sấy năng lượng mặt trời đối lưu, (3) Sấy năng lượng mặt trời hỗn hợp. [@raghavan_effect_1997] Một số thiết bị mới được phát triển gần đây như sấy nhà kính đối lưu cưỡng bức, [@morad_thermal_2017] sấy đường hầm năng lượng mặt trời đối lưu cưỡng bức [@raghavan_effect_1997] và sấy tâng sôi hỗ trợ năng lượng mặt trời. [@ceylan_solar-assisted_2016] Nhiều loại dược liệu đã được nghiên cứu sử dụng phương pháp này ví dụ cỏ xạ hương và bạc hà (máy sấy năng lượng mặt trời đối lưu cưỡng bức ở chế độ gián tiếp) [@el-sebaii_experimental_2013], bạc hà (sử dụng máy sấy nhà kính đường hầm năng lượng mặt trời) [@morad_thermal_2017], trà java (máy sấy nhà kính năng lượng mặt trời với máy bơm nhiệt tích hợp) [@tham_effect_2017], rau mùi tây (máy sấy bơm nhiệt mặt trời) [@sevik_experimental_2014], hương thảo (bộ thu năng lượng mặt trời với máy sưởi phụ, ở 50--80 C) [@mghazli_drying_2017], nghệ tây (máy sấy năng lượng mặt trời lai quang điện-nhiệt hỗ trợ bơm nhiệt) [@mortezapour_saffron_2012] và misai kucing (máy sấy bơm nhiệt hỗ trợ năng lượng mặt trời) [@gadde_alternatives_2017]. Sấy lá bạc hà trong nhà kính bằng đường hầm mặt trời cho thấy giời giảm giảm 23-25% so với sấy nhà kính thông thường. [@morad_thermal_2017] Máy sấy năng lượng mặt trời sử dụng kết hợp thêm bơm nhiệt có thể tạo ra hệ thống sấy liên tục, chất lượng tốt hơn ví dụ độ co ngót, hỏng do nhiệt và mùi vị nếu so phương pháp sấy năng lượng mặt trời thông thường. [@sevik_experimental_2014] Máy sấy năng lượng mặt trời có thể kết hợp với bộ thu năng lượng mặt trời, bộ trao đổi nhiệt, gương phản xạ cùng bộ gia nhiệt giúp giảm 50% thời gian sấy hoa cúc khi so với phơi năng. Chất lượng sản phẩm có hàm lượng tinh dầu cao hơn ví dụ hoa hồng và sả khô có chất lượng tốt hơn trong máy sấy năng lượng mặt trời dạng thùng. [@ahmed_drying_2001; @janjai_performance_2005] Hệ thống sấy mặt trời kết hợp máy sấy và hút ẩm đem lại màu sắc tốt hơn cho lá pegaga khô do nhiệt độ sấy thấp hơn và độ ẩm thấp. [@thamkaew_review_2021] Các thiết bị mới sử dụng hiệu quả năng lượng mặt trời hơn tuy nhiên các nghiên cứu về ảnh hưởng quy trình tới mùi thơm và màu sắc thảo dược vẫn chưa có nhiều nghiên cứu.

**Sấy bằng khí nóng**

*Thuật ngữ tiếng Anh:* Hot-air drying

Các phương pháp sử dụng năng lượng mặt trời đều có nhược điểm thời gian sấy quá dài. Trong công nghiệp, phương pháp làm khô dược liệu phổ biến được áp dụng chính là sử dụng lò sấy (còn gọi là "sấy đối lưu" hoặc "sấy bằng khí nóng"). Phương pháp này phổ biến tại các quốc gia không đủ ánh sáng mặt trời như các quốc gia ôn đới. [@orphanides_drying_2016] Ưu điểm chính phương pháp này sẽ kiểm soát được quy trình đặc biệt các thông số quan trọng như nhiệt độ, thời gian và tốc độ thổi gió. Các thông số này ảnh hưởng tới đặc tính của sản phẩm và có thể tối ưu hóa quy trình sản xuất để nâng cao chất lượng sản phẩm. [@orphanides_drying_2016]  Tuy nhiên, chất bay hơi trong sản phẩm khi sấy bằng phương pháp này thấp. [@chua_influence_2019] Sấy bằng khí nóng gây ra giảm mùi thơm dược liệu đồng thời nhiệt độ sấy cao có thể dẫn tới biến đổi màu sắc. [@fennell_assessing_2004] Để khắc phục, nhiệt độ sấy thường từ 35-50 $^oC$ để hướng tới giảm thiểu ảnh hưởng tới các chất nhạy cảm với nhiệt. [@muller_development_1989] Lưu thông khí giúp luồng khí nóng phân tán đều thúc đẩy quá trình bay hơi ẩm kèm theo đó cả các chất dễ bay hơi [@orphanides_drying_2016] và tạo ra môi trường thích hợp cho các phản ứng oxy hóa (Antal 2010). Thêm nữa, phương pháp này có nhược điểm không khí nóng làm co rút sản phẩm và tốn năng lượng. [@orphanides_drying_2016] Hiện tại, các cải tiến đang tập trung vào giảm tiêu thụ năng lượng, tăng hiệu quả sấy cũng như giảm thời gian sấy. [@won_accelerated_2015] Trong phần dưới đây, ảnh hưởng của các thông số sấy khô bằng khí nóng đối với sự suy giảm chất lượng của các loại thảo mộc khô được bàn luận. 

*Ảnh hưởng nhiệt độ và độ ẩm tới chất lượng dược liệu* 

Theo khuyến nghị, nhiệt độ sấy được đặt tại 40-60 $^oC$. [@shaw_drying_2007] Tuy nhiên, nhiệt độ sẽ dẫn đến những thay đổi không mong muốn về mùi thơm của các loại thảo dược khô. [@antal_effect_2011] Các báo cáo thấy rằng tăng nhiệt độ sấy từ 40 đến 60 $^oC$ dẫn đến tổng hàm lượng các chất dễ bay hơi thấp hơn, ít mùi thơm tươi mát hơn và tăng vị cay, ngọt và có hương gỗ trong lá húng quế khô. [@calin-sanchez_volatile_2012] Các kết quả này cũng phù hợp với một số dược liệu khác như bạc hà (nhiệt độ sấy tăng từ 30 lên 70 $^oC$) [@rohloff_effect_2005], lá chanh kaffir (từ 50 lên $70^oC$) [@jirapakkul_effect_2013], cây xô thơm Achillea (từ 35 đến 45 $^oC$), và cây xô thơm (từ 30 đến 60 $^oC$). [@venskutonis_effect_1997] Nhiệt độ sấy cao hơn 60 $^oC$ làm mất hầu hết các hợp chất dễ bay hơi trong khô (*Allium schoenoprasum* L., *Anethum Graveolens* L., *Anthriscus cerefolium* (L.) Hoffm., *Artemisia dracunculus* L., *Coriandrum sativum* L., *Levisticum officinale* Koch. *Mentha spicata* L., *Origanum majorana* L., *Petroselinum crispum* (Mill.) Nym. ex A. W. Hill, *Salvia officinalis* L., *Satureja hortensis* L., và *Thymus vulgaris* L.). [@deans_effect_1991] Ngoài ra, nhiệt độ sấy tăng gây ra nhiều thay đổi không mong muốn khác trong các sản phẩm chẳng hạn như các mô bị phân hủy, [@prothon_mechanisms_2003] các hợp chất hoạt tính sinh học giảm [@tambunan_freeze_2001], và màu sắc thay đổi. [@calin-sanchez_volatile_2012] Màu của lá khô *Moringa Oleifera* tại 40 $^oC$ tốt hơn so với nhiệt độ 50 và 60 $^oC$. [@ali_drying_2014] Về mặt cấu trúc, sấy ở nhiệt độ 60$^oC$ lá *Vernonia amygdalina* gây tổn thương bề mặt biểu bì, làm co lại các tế bào trichome và mức độ biến dạng thành tế bào cao hơn so với 40 và 50 $^oC$. [@alara_mathematical_2019] Tăng nhiệt độ sấy làm giảm khả năng chống oxy hóa của nhiều loại dược liệu như hương thảo (*Rosmarinus officinalis*), ngải cứu (*Leonurus hearta*) và bạc hà (*Mentha piperita*) khi so sánh giữa nhiệt độ 40 $^oC$ và 70 $^oC$. [@yi_effects_2011] Tổng hàm lượng phenol, salicylat và quercetin giảm khi sấy cỏ ngọt (*Filipendula ulmaria*) và liễu (*Salix alba*) (tổng hàm lượng phenol, salicylat và quercetin tại nhiệt độ 70$^oC$) khi đối chiếu với $30^oC$. [@harbourne_effect_2009]  Ngược lại, nhiệt độ tăng có thể làm tăng hàm lượng chất thơm. Đây là trường hợp của cỏ roi chanh, hàm lượng chất dễ bay hơi cao hơn khi sấy ở nhiệt độ $50^oC$ khi so với 30 và 40 $^oC$. [@shahhoseini_qualitative_2013] Kết quả tương tự cũng được quan sát thấy ở lá cỏ xạ hương được sấy khô bằng không khí nóng ở 30, 38 và 45 $^oC$. [@piga_influence_2007] Tác động tích cực của việc tăng nhiệt độ sấy khô cũng được quan sát thấy đối với quá trình chuyển hóa chất. Trà thảo mộc chứa một số loại thảo mộc bao gồm *Centella asiatica, Mentha arvensis và Polygonum* có hàm lượng hóa một số chất gồm chất diệp lục, acid ascorbic, niacin, riboflavin và carotenoids cao hơn khi sấy tại 70$^oC$ khi so với nhiệt độ 50$^oC$. [@mahanom_effect_1999]


**Sấy lạnh**

Sấy lạnh được đề xuất như phương pháp làm khô mà vẫn giữ được mùi thơm do sử dụng nhiệt độ thấp.[@antal_inspection_2020] Sản phẩm thu được mùi hương tốt hơn so với phương pháp sấy khác như lá bạc hà trong nghiên cứu của Antail *et al.* năm 2011 [@antal_effect_2011] hoặc lá húng quế. [@di_cesare_changes_2003] Sấy lạnh cho thấy thành phần hóa học của tinh dầu lá húng quế tím và xanh tốt hơn so với phơi nắng, phơi trong bóng râm, sấy không khí nóng ở 40 và 60 $^oC$, và sấy vi sóng ở 500 và 700 W. [@ghasemi_pirbalouti_effects_2013] Kết quả tương tự cũng được thể hiện đối với rau mùi Iran. [@ghasemi_pirbalouti_effect_2017] Cỏ xạ hương sấy lạnh chỉ giảm 1-3% tổng hàm lượng chất bay hơi. [@venskutonis_influence_1996] Kinh giới sấy lạnh cho thấy khả năng giữ màu tốt hơn so với sấy khô bằng không khí và sấy chân không kết hợp vi sóng. [@yousif_headspace_2000] Lá *Andrographis paniculata* sấy lạnh cho thấy ít co rút hơn và độ xốp cao hơn so với sấy khô bằng khí nóng. [@tummanichanont_effects_2017] Tuy nhiên, so với sấy bằng vi sóng, sấy lạnh được cho tạo ra các sản phẩm sấy khô có chất lượng thấp hơn. Trong trường hợp cỏ xạ hương (*Thymus daenensis*), lá sấy lạnh chứa hàm lượng tinh dầu cao và màu sắc đẹp nhưng mùi thơm kém hẫp dẫn hơn khi sấy khô bằng phương pháp sấy vi sóng. [@rahimmalek_evaluation_2013] Kết quả tương tự cũng quan sát thấy ở húng quế trong đó lá sấy lạnh có hàm lượng các hợp chất dễ bay hơi đặc trưng thấp hơn so với lá sấy khô bằng lò vi sóng gồm hàm lượng eucalyptol, linalool, eugenol và methyl eugenol. Trong cùng một nghiên cứu, người ta cũng phát hiện ra rằng sấy lạnh làm giảm sắc tố diệp lục của các sản phẩm sấy khô nhiều hơn so với sấy bằng vi sóng. [@di_cesare_changes_2003] Quá trình sấy lạnh có thể giảm các hợp chất tạo hương thơm của các loại thảo mộc khô. [@calin-sanchez_volatile_2012] Báo cáo trên mùi tây sấy lạnh làm mất đi các thành phần dễ bay hơi chính như p-men-tha-1,3,8-triene và apiole. [@diaz-maroto_effect_2002] Giảm mùi thơm cũng được quan sát thấy ở húng quế ngọt sất khô (*Ocimum basilicum* L.) và lá nguyệt quế. [@diaz-maroto_effect_2002] Hàm lượng các hoạt chất có hoạt tính sinh học cao hơn khi sấy lạnh. Khi so sánh lá húng tây sấy lạnh (*Thymus vulgaris*) với phương pháp khác, sản phẩm sấy lạnh có hàm lượng thymol cao hơn so với những lá thu được bằng cách sấy khô trong lò ở $30-50^oC$ và sấy khô trong [@ibanez_supercritical_1999] bóng râm. Các kết quả tương tự cũng quan sát thấy ở lá hương thảo sấy lạnh có khả năng chống oxy hóa cao hơn so với sấy khô bằng không khí nóng ở 45 $^oC$ [@ibanez_supercritical_1999] và lá bạc hà sấy lạnh so với phơi nắng, sấy trong bóng râm, sấy đối lưu và sấy bằng lò vi sóng. [@orphanides_effect_2013] Ngược lại, sấy lạnh làm giảm các hoạt chất có hoạt tính sinh học trong các loại thảo dược thuộc họ Lamiaceae bao gồm hương thảo, oregano, kinh giới, xô thơm, húng quế và cỏ xạ hương (so sánh với sấy khô bằng không khí nóng, chân không). Các mẫu sấy khô có tổng hàm lượng phenolic, acid rosmarinic và khả năng chống oxy hóa thấp hơn so với các phương pháp sấy khô khác. [@li_phytogenic_2015]


**Sấy vi sóng**

*Thuật ngữ tiếng Anh:* Microwave drying

Sấy vi sóng là một kỹ thuật sấy khô hiện đại trong lĩnh vực dược liệu. [@moses_novel_2014] Phương pháp này cho phép nước bay hơi nhanh hơn và thời gian sấy tương đối ngắn so với phương pháp sấy đối lưu, phơi trong bóng râm và nắng, sấy đông lạnh. Mức năng lượng sử dụng cũng giảm khi áp dụng kỹ thuật này. [@di_cesare_changes_2003] Các sản phẩm được sấy khô bằng vi sóng ít co ngót hơn, màu sắc tốt hơn và khả năng bù nước tốt hơn so với sấy khô bằng không khí nóng. [@k_kathirvel_microwave_2006] Chất lượng của các sản phẩm sấy khô bằng vi sóng ảnh hưởng bởi các thông số như công suất vi sóng (W), thời gian sấy, độ ẩm ban đầu và tính chất điện môi của vật liệu. [@moses_novel_2014] Công suất vi sóng tăng từ 360 lên 900W giúp giảm 64% thời gian làm khô rau mùi tây. Màu sắc sản phẩm sấy khô bằng lò vi sóng có màu sắc tốt hơn và màu đậm hơn một chút so với rau mùi tây tươi. [@soysal_microwave_2004] Kết quả tương tự cũng được quan sát thấy ở rau mùi [@sarimeseli_microwave_2011] khi tăng công suất vi sóng từ 180 lên 360 W dẫn đến hệ số khuếch tán tăng lên trong khi khả năng bù nước của lá rau mùi khô giảm. Chất lượng của các loại thảo mộc sấy khô bằng vi sóng cao hơn so với các phương pháp sấy khô khác. Lá húng quế sấy khô bằng vi sóng có khả năng giữ lại các chất dễ bay hơi cao hơn so với các sản phẩm sấy khô từ phương pháp sấy đối lưu tại $50^oC$ và sấy lạnh. Cũng trong nghiên cứu này, lá sấy khô bằng vi sóng ít thay đổi màu sắc hơn so với sản phẩm sấy khí nóng. Màu sắc ít thay đổi có thể là hệ quả của thời gian sấy ngắn hơn khi sấy bằng vi sóng. [@di_cesare_changes_2003] Một nghiên cứu so sánh giữa sấy vi sóng với công suất vi sóng 700 W, 2450 MHz, phơi nắng và sấy khí nóng ở $50^oC$ của lá hương thảo cho thấy màu sắc của lá hương thảo sấy bằng vi sóng tốt hơn so với các sản phẩm sấy khô bằng khí nóng. [@arslan_evaluation_2008] Một kết quả tương tự cũng được quan sát thấy ở lá rau mùi sấy khô bằng vi sóng ở công suất 295W cho thấy khả năng giữ màu tốt hơn so với mẫu sấy khí nóng ở $50^oC$. Sấy vi sóng cũng có lợi thế về mặt bảo quản hoặc hàm lượng hoạt chất. Hàm lượng $trans-\beta-carotene$ và sắc tố cao hơn trong lá mùi khi sấy vi sóng ở 850W khi so sánh với sấy khí nóng ở $45^oC$. [@divya_carotenoid_2012] Kết quả tương tự khi sấy vi sóng 850W ở lá xô thơm khi tổng hàm lượng phenolic và flavonoid cũng như tác dụng chống oxya cao hơn khi sấy khí nóng ở 45 $^oC$. [@sukadeetad_effect_2018] Lò vi sóng có thể kết hợp với phương pháp sấy khác như sấy khô bằng khí nóng khi sấy sơ bộ ban đầu để giảm độ ẩm hoặc giai đoạn sấy cuối. Tuy nhiên, nhược điểm lớn của phương pháp sấy vi sóng là khả năng gia nhiệt không đồng đều, dẫn đến hình thành chênh lệch nhiệt độ trong sản phẩm, đặc biệt là sản phẩm có kích thước lớn. Việc gia nhiệt không đồng đều này có thể dẫn đến sản phẩm bị mất nước không đều, quá nóng và giảm chất lượng. [@ozkan_microwave_2007] Tuy nhiên, sự quan tâm đến việc sấy khô các loại thảo mộc bằng vi sóng đã tăng lên trong những năm gần đây. Điều này có thể là do các loại thảo dược thường có kích thước nhỏ hơn và mỏng hơn so với hầu hết các loại thực phẩm rắn khác. Do đó, việc gia nhiệt không đồng đều có thể không phải là một nhược điểm lớn đối với việc sấy khô các loại thảo dược bằng vi sóng. Tuy nhiên, sấy vi sóng đối với một số loại thảo mộc, chẳng hạn như kinh giới [@raghavan_effect_1997] và hương thảo [@rao_rosemary_1998], được báo cáo giảm nhóm chất thơm nhiều hơn so với nhiều phương pháp sấy khô, bao gồm cả sấy đối lưu, sấy trong bóng râm và phơi ngoài nắng. Thời gian sấy bằng vi sóng nhanh hơn nhiều so với tất cả các phương pháp sấy vừa đề cập. Tuy nhiên, cần nghiên cứu thêm về các thông số sấy vi sóng để tối ưu hóa quy trình và cải thiện chất lượng của sản phẩm sấy khô. [@moses_novel_2014]

**Sấy vi sóng trong chân không**

*Thuật ngữ tiếng Anh:* Microwave-vacuum drying

Đây là phương pháp kết hợp vi sóng tạo nhiệt sấy khô và tạo chân không để tăng tốc độ bay hơi nước. [@orphanides_drying_2016] Kết hợp với chân không dẫn đến tốc độ sấy khô nhanh hơn so với sấy khí nóng và sấy vi sóng. [@soysal_microwave_2004] So với sấy khô bằng khí nóng, sấy vi sóng trong chân không có thể giảm thời gian sấy từ 70--90% và cũng tạo ra các sản phẩm có chất lượng tốt hơn. [@giri_drying_2007] Thymol trong *L. berlandieri* cao hơn 1,3 lần so sấy khô bằng khí nóng. [@yousif_headspace_2000] Sấy khô lá bạc hà bằng lò vi sóng trong chân không giúp sản phẩm sấy khô giữ được màu tốt hơn so với sấy khô bằng khí nóng. Ảnh SEM của các sản phẩm có độ xốp hơn và ít bị xẹp hơn so với các mẫu được sấy khô bằng khí nóng. [@therdthai_characterization_2009] Tuy nhiên, hạn chế chính của phương pháp này là công suất của bơm chân không. Với lượng ẩm ban đầu cao từ nguyên liệu thảo dược tươi, bơm chân không có thể nhanh chóng vượt quá công suất thiết kế, dẫn đến quy trình kém hiệu quả hơn. Ngược lại, sấy vi sóng trong vi sóng cũng được báo cáo gây giảm chất lượng sản phẩm sấy khô ở một số loại thảo mộc, chẳng hạn như hương thảo. Các hợp chất dễ bay hơi của hương thảo trong sản phẩm cuối của sấy vi sóng trong chân không thấp hơn với phương pháp sấy khô bằng khí nóng tại 60 $^oC$. Tuy nhiên, cũng trong nghiên cứu đó cho thấy kết hợp giữa sấy khí nóng sơ bộ và sấy khô hoàn toàn bằng vi sóng trong chân không lại có hàm lượng chất dễ bay hơi cao hơn trong sản phẩm cuối. Tóm lại, sấy vi sóng trong chân không là một phương pháp sấy kết hợp đầy hứa hẹn với tiềm năng tốt để trở thành một phương pháp phù hợp để sấy khô các loại thảo dược. 

**Sấy khô dược liệu có trợ giúp bởi máy bơm**

*Thuật ngữ tiếng Anh:* Heat-pump-assisted drying

Sấy khô có trợ giúp bởi máy bơm là một kỹ thuật sấy dùng các loại sinh nhiệt khác nhau kết hợp với máy bơm để tăng hiệu quả sử dụng. Máy bơm thường được kết hợp với bộ sấy khí nóng để tăng nhiệt độ không khí đầu vào. [@fatouh_herbs_2006] Máy sấy bơm nhiệt phù hợp quy mô công nghiệp do hoạt động với khả năng điều chỉnh nhiệt độ sấy và vận tốc khí thổi. [@fatouh_herbs_2006] Một lợi ích khác của máy sấy bơm nhiệt chính là khả năng hút ẩm không khí tại đầu ra của thiết bị. [@fatouh_herbs_2006] Chất lượng sản phẩm có chất lượng tốt hơn do khả năng kiểm soát chất lượng không khí trong buồng sấy. Sấy trà java *(Orthosiphon aristatus)* bằng năng lượng mặt trời kết hợp với bơm tuần hoàn cho thấy khả năng kiểm soát độ ẩm trong buồng sấy tốt hơn máy sấy năng lượng mặt trời thông thường đặc biệt là ban đêm. Hệ thống bơm hút ẩm làm giảm độ ẩm buồng sấy tương đối từ 10-15% và có thể duy trì độ ẩm khoảng 65%. Hơn nữa, tốc độ làm khô của hệ thống sấy bằng năng lượng mặt trời tích hợp bơm nhiệt tốt hơn 3-4 lần so với tốc độ làm không của sấy năng lượng thông thường. [@tham_effect_2017] Trọng tâm của các nghiên cứu gần đây là làm khô bằng bơm nhiệt liệu có ảnh hưởng tới hàm lượng các hoạt chất trong dược liệu không. [@gan_drying_2017; @klungboonkrong_drying_2018; @tummanichanont_effects_2017] Hầu hết các nghiên cứu cho thấy các sản phẩm tốt hơn về mặt bảo quản các hợp chất khi so sánh với các phương pháp sấy khô khác, chẳng hạn trường hợp sấy misai kucing so với sấy khô bằng năng lượng mặt trời [@torki-harchegani_infrared_2017] và *Andrographis paniculata* so với sấy khô bằng không khí nóng, sấy khô bằng vi sóng và sấy đông lạnh [@tummanichanont_effects_2017]. Hàm lượng andrographolide, neoandrographolide và tổng số phenolics trong lá *Andrographis paniculata* cao hơn khi sử dụng sấy bơm nhiệt và hút ẩm tại nhiệt độ 40, 50 và 60 $^oC$ so với các mẫu được sấy khô bằng không khí nóng ở cùng nhiệt độ sấy. Cũng trong nghiên cứu này cho thấy hình dạng ban đầu của tế bào nhu mô sản phẩm sấy khô tốt hơn so với sấy khô bằng không khí. Trên trà javaa, tổng hàm lượng phenolic và hoạt tính chống oxy hóa của sản phẩm sấy ở nhiệt độ $60^oC$ khi kết hợp bơm nhiệt và hút ẩm tương đương với sấy lạnh. [@klungboonkrong_drying_2018] Ngoài ra, hệ thống này giúp giảm 44,8% thời gian sấy so với sấy đối lưu ở cùng nhiệt độ sấy. Hơn nữa, vi cấu trúc của sản phẩm được sấy khô có cấu trúc tế bào đầy đủ và đều đặn hơn so với sản phẩm sấy khô đối lưu. Nhìn chung, sấy khô kết hợp với bơm mang lại kết quả đầy hứa hẹn để cải thiện hàm lượng các hợp chất có hoạt tính sinh học và đặc tính cấu trúc của sản phẩm sấy khô. Tuy nhiên, cần có các nghiên cứu sâu hơn về kỹ thuật sấy khô này trong các loại thảo dược để kiểm tra tác động của quá trình đối với mùi hương của chúng. 

**Sấy bằng tia hồng ngoại**

*Thuật ngữ tiếng Anh:* Infrared drying

Ưu điểm chính của phương pháp này là khả năng thích ứng, đơn giản, tốc độ gia nhiệt nhanh và tốc độ sấy khô nhanh. [@miraei_ashtiani_analyzing_2017] Quá trình diễn ra khi năng lượng sinh ra từ bức xạ tại bước sóng hồng ngoại truyền và hấp thụ vào thảo dược sẽ sinh ra nhiệt từ bên trong do sự thay đổi trạng thái dao động của phân tử. [@krishnamurthy_infrared_2008] Hiệu quả sử dụng năng lượng cao hơn so với sấy khí nóng. Tuy nhiên, số lượng nghiên cứu về sấy thảo dược bằng tia hồng ngoại chưa nhiều. Khi sấy lá bạc hà, hiệu quả năng lượng và tốc độ sấy của sấy hồng ngoại cao hơn so với sấy đối lưu tại nhiệt độ sao sánh là 30, 40, 50 $^oC$. [@miraei_ashtiani_analyzing_2017] Trong sấy khô nghệ tây bằng tia hồng ngoại, sản phẩm có hàm lượng crocin và safranal cao hơn. [@torki-harchegani_infrared_2017] Đây là các hợp chất chính góp phần tạo ra tác dụng của nghệ tây khô. Phương pháp này cần chú ý độ dày lớp nguyên liệu do tia hồng ngoại thích hợp di chuyển trong lớp dược liệu mỏng và diện tích tiếp xúc. Thêm nữa, việc nâng nhiệt độ không đồng đều có thể dẫn tới suy mùi hương sản phẩm theo báo cáo của Chua *et al.* vào năm 2019. [@chua_influence_2019]

**Sấy tầng sôi**

*Thuật ngữ tiếng Anh:* Fluidized bed drying

Sấy tầng sôi được ứng dụng trong công nghiệp thực phẩm với nhiều loại nông sản và cũng được triển khai với một số thảo dược. [@gangopadhyay_comparative_1979] Quá trình này được thực hiện bằng cách cho luồng khí nóng với tốc độ cao (đủ cao để loại hơi nước) đến khay sấy nơi đặt thảo dược. Tốc độ sấy của phương pháp này cao hơn nhiều so với sấy đối lưu truyền thống do tốc độ gia nhiệt nhanh của phương pháp. Trên lá sim chanh, tăng nhiệt độ sấy tại 30, 40 và 50 $^oC$ dẫn tới hàm lượng citral giữ cao hơn (hương thơm của cam quýt) trong sản phẩm sấy khô. [@buchaillot_drying_2009] Tuy nhiên, tại nhiệt độ thấp hơn (30 $^oC$) giữ màu sắc sản phẩm tốt hơn và nhiệt độ sấy cao nhất ($50^oC$) có chất lượng màu kém nhất. Không phải thảo dược nào cũng phù hợp với phương pháp này. Với thảo dược có độ ẩm cao, diện tích mặt thô ráp và lớn có thể dẫn tới thông khí kém. Để khắc phục, một thiết bị rung đã được phát triển (tên tiếng anh là Vibratory fluidized bed). [@de_la_fuente-blanco_food_2006] Thiết bị như vậy giúp giảm độ ẩm và đồng nhất độ ẩm trong suốt quá trình sấy. Tuy nhiên, hàm lượng hoạt chất có thể sụt giảm với phương pháp này. 

**Sấy siêu tới hạn với Carbon dioxide** 

*Thuật ngữ tiếng Anh:* Supercritical CO2 drying -scCO2

Quá trình làm khô bằng phương pháp này có sử dụng CO2 siêu tới hạn làm môi trường. Ưu điển phương pháp này là nhiệt độ sấy thấp, lượng oxy thấp, độ co rút sản phẩm thấp. Một vài nghiên cứu về làm khô thảo dược bằng scCO2 đã được tiến hành. Việc sấy khô húng quế bằng scCO2 đã được báo cáo [@busic_comparative_2014] khi so với các kỹ thuật sấy khô khác bao gồm sấy khí nóng ($40^oCC$ trong 26 giờ) và sấy lạnh ($20^oC$ ở 0,005 bar trong 4 ngày). Kết quả cho thấy rằng chất lượng húng quế khô tốt nhất đạt được bằng cách sấy đông lạnh, tiếp theo là sấy khô bằng scCO2, trong khi sấy khí nóng cho thấy chất lượng sản phẩm sấy khô kém nhất khi xét đến các yếu tố bảo quản màu sắc, hàm lượng hoạt chất. Tuy nhiên, có ý kiến cho rằng sấy khô bằng scCO2 là quy trình sấy khô phù hợp nhất trong số ba phương pháp được nghiên cứu do chất lượng thảo mộc khô có thể chấp nhận được và thời gian sấy ngắn (2-3h) trong khi sấy lạnh (4 ngày) và sấy khí nóng (26 h). Một nghiên cứu khác về làm khô bằng scCO2 kết hợp xử lý siêu âm trong lá mùi. [@michelino_high_2018] Kết quả cho thấy phương pháp sấy scCO2 vô hiệu hóa vi sinh vật tốt gồm nấm men, nấm mốc và vi khuẩn ưa ấm đã giảm trong quá trình sấy khô. Tuy nhiên, việc phân tích các đặc tính cảm quan và hàm lượng hoạt chất trong các sản phẩm sấy khô chưa được báo cáo.

**Sấy dựa vào tần số vô tuyến**

*Thuật ngữ tiếng Anh:* Radio-frequency drying

Sấy dựa vào tần số vô tuyến (RF) là phương pháp kết hợp việc sử dụng nhiệt do tần số vô tuyến tạo ra và sấy đối lưu. Quá trình gia nhiệt tần số vô tuyến phụ thuộc vào tính chất điện môi của thảo dược tương tự gia nhiệt vi sóng chỉ có khác biệt về tần số. [@nijhuis_approaches_1998] Gia nhiệt bằng tần số vô tuyến có thể giúp tăng tốc độ sấy khô, đặc biệt là trong giai đoạn tốc độ sấy giảm trong khi sấy khí nóng. [@glenn_radio_2015] Một nghiên cứu duy nhất so sánh giữa hiệu quả sử dụng phương pháp RF, đối tượng nghiên cứu là rau thì là. [@madhava_naidu_effect_2016] Sấy RF cho thấy tốc độ sấy nhanh hơn so với sấy khí nóng ở 50 $^oC$. Tuy nhiên, rau thì là khô bằng RF cho thấy hàm lượng hoạt chất thấp nhất (bao gồm Chlorophyll a và b, carotenoid và acid ascorbic) so với các sản phẩm sấy khô từ sấy khí nóng (50 $^oC$, với độ ẩm 58--63% và độ ẩm 28--30% RH) và sấy hồng ngoại. Theo kết quả, sấy khô RF có thể không phải là phương pháp sấy khô thích hợp cho các loại thảo mộc khi xét đến Chlorophyll và thay đổi màu sắc. 

**Kết hợp các phương pháp**

*Thuật ngữ Tiếng Anh:* Hybrid drying methods

Phương pháp sấy kết hợp là sử dụng hai hay nhiều kỹ thuật sấy để khắc phục vấn đề trong từng giai đoạn. Sấy kết hợp bơm nhiệt có thể hỗ trợ các phương pháp như sấy năng lượng mặt trời, sấy chân không bằng vi sóng hoặc sấy bằng tần số vô tuyến. Nhưng kỹ thuật sấy này được quan tâm do khả năng rút ngắn thời gian xử lý, giảm thiểu sự suy giảm chất lượng và duy trì hiệu quả của quy trình. [@chou_new_2001] Hiện tại, ba phương pháp nhận được nhiều sự quan tâm nhất có lẽ là sấy khô bằng năng lượng mặt trời, sấy khô bằng lò vi sóng và sấy khô sử dụng bơm nhiệt. [@chou_new_2001] Tuy nhiên, thông tin về ảnh hưởng của các công nghệ lai này đối với chất lượng của các loại thảo mộc khô còn hạn chế. 

## 5.2 Chuẩn hóa cao chiết bằng kỹ thuật làm khô

### 5.2.1 Giới thiệu

Từ xa xưa, thảo mộc đã được sử dụng để chữa bệnh cho con người và là nền tảng của các hệ thống y học cổ truyền hàng nghìn năm như Ayurveda, Chinese và Unani. Cho đến trước thế kỷ 19, thảo mộc là nguồn cung cấp chính các sản phẩm chữa bệnh chính. Sau đó, giai đoạn vàng của thuốc tổng hợp hóa dược chiếm ưu thế đặc biệt là các quốc gia phương Tây làm cho thuốc tử thảo mộc bị lãng quên. Tuy nhiên, trong vòng 40 năm qua các thuốc từ thảo mộc đã trở lại do bằng chứng về tính hiệu quả, an toàn, lý do văn hóa, chi phí thấp mặc dầu vẫn có các hoài nghi về tính hiệu quả của một số liệu pháp. Ngày nay, giá trị thương mại của các sản phẩm từ cây thuốc đã vượt quá hàng chục tỷ đôla Mỹ và ngày càng tăng. [@vasisht_current_2016] Tổ chức Y tế Thế giới (WHO) khuyến khích các nước đang phát triển sử dụng thuốc thảo mộc truyền thống để đáp ứng nhu cầu mà các hệ thống chăm sóc sức khỏe hiện đại chưa đáp ứng được cũng góp phần vào sự tăng trưởng này. [@ekor_growing_2014] Khoảng 70-80% dân số thế giới ở các nước đang phát triển chủ yếu dựa vào các liệu pháp tự điều trị trong chăm sóc sức khỏe ban đầu của họ. [@sasidharan_extraction_2011] Y học cổ truyền chủ yếu dựa vào thảo mộc và các dẫn xuất của chúng với nhiều tên thuật ngữ khác nhau, chẳng hạn như dược liệu, thảo mộc, thảo dược, vị thuốc. [@calixto_efficacy_2000] Người ta đã báo cáo rằng có khoảng 35.000 đến 70.000 loài thực vật được sử dụng để điều trị bệnh trên toàn thế giới, nhưng chỉ một số ít được nghiên cứu khoa học để đánh giá chất lượng, độ an toàn và hiệu quả của chúng. [@alamgir_therapeutic_2017]  Do việc phát triển các phương thuốc thảo dược tiêu chuẩn hóa đòi hỏi đầu tư và công nghệ thấp hơn đáng kể so với một loại thuốc hóa dược, nên chúng hoàn toàn khả thi đối với các quốc gia kém phát triển và đang phát triển. Các quy định về dược liệu đã được thực hiện bởi một số quốc gia, bao gồm cả Việt nam (các chuyên luận dược liệu trong dược điển) giúp thiết lập các công cụ để hướng dẫn sản xuất và đảm bảo tính an toàn, hiệu quả và chất lượng của chúng. [@carvalho_regulation_2011]


### 5.2.2 Yếu tổ ảnh hưởng tới hàm lượng hoạt chất tới dược liệu tươi

Hoạt chất có tác dụng sinh học từ thảo dược được tạo ra bởi quá trình trao đổi thứ cấp bằng cách sử dụng các con đường sinh tổng hợp riêng biệt. Quá trình tạo ra hoạt chất này trong thực vật bị ảnh hưởng bởi nhiều yếu tố như thổ nhưỡng, dinh dưỡng, nguồn nước, ánh nắng mặt trời, chu kỳ sinh học và thời điểm thu hái. Các ảnh hưởng này có mối liên hệ chặt chẽ với nhau như chu kỳ sinh học ảnh hưởng bởi nhiệt độ trong năm cũng như nguồn nước chi phối bởi tác động thời tiết. Do đó, các nghiên cứu phải được thực hiện để xác định được điều kiện thích hợp để cây phát triển đồng thời tối ưu hóa sinh tổng hợp nhiều hoạt chất nhất có thể. Các đánh giá toàn diện về tác động của tính thời vụ và các yếu tố khác như tuổi cây và giai đoạn phát triển, nhiệt độ, nguồn nước và tỷ lệ bức xạ có thể được tìm thấy trong tài liệu về nuôi trồng dược liệu. [@liebelt_only_2019; @li_effect_2020]


### 5.2.3 Chuẩn hóa sản phẩm từ dược liệu

Các sản phẩm có nguồn gốc từ thảo dược ngày càng tăng dẫn tới sự gia tăng đáng kể yêu cầu liên quan đến kiểm soát chất lượng. Để được ứng dụng làm nguyên liệu trong thực phẩm, dược phẩm hay mỹ phẩm, các sản phẩm này phải được tiêu chuẩn hóa với các đặc tính có thể định tính và định lượng các thành phần hoạt chất chính. Hoạt tính sinh học của sản phẩm từ thảo dược thường được đánh giá vượt trội hơn khi so sánh với hoạt chất đơn độc do đa thành phần- đa đích. Ngoài tiêu chuẩn hóa chất lượng, việc giám sát quy trình sản xuất cũng được coi trọng từ khâu thu hái, chế biến dược liệu tới chiết xuất và bào chế và cuối cùng là khâu bảo quản. Tất cả các khâu sản xuất hiện tại đều hướng tới tác động tối thiểu tới môi trường từ khâu dược liệu thô đến thành phẩm. Yếu tố bảo vệ môi trường của sản phẩm được xem là nhu cầu của người tiêu dùng lẫn cơ quan quản lý. Mặc dù thông tin được trình bày trong chương này tập trung vào các loại thuốc thảo dược, nhưng các bước chế biến là giống nhau và có thể áp dụng sang quy trình sản xuất công nghiệp khác. 

### 5.2.4 Chuẩn hóa cao chiết bằng kỹ thuật làm khô

Sau khi chiết xong, loại bỏ dung môi là bước quan trọng trong quá trình sản xuất thuốc từ dược liệu mặc dù có thể bào chế dưới dạng dung dịch vẫn được một số quốc gia ưu chuộng. Khi đó sản phẩm có thể chuyển sang dạng bào chế quy ước dạng rắn như viên nén, viên nang dễ dàng hơn. Quá trình làm khô tác động đáng kể tới chất lượng cao như độ ẩm, hàm lượng hoạt chất, thể tích, tỷ trọng cũng như màu sắc. [@cortes-rojas_physicochemical_2012; @souza_spouted_2005] Quá trình loại bỏ dung môi có thể sử dụng một số thiết bị gồm sấy phun (SD), đông khô (FD), sấy tầng sôi và sấy vi sóng. [@kemp_drying_2017] Sấy phun được áp dụng phổ biến trong công nghiệp trong khi đông khô lại sử dụng nhiều trong các nghiên cứu. Sấy tầng sôi được coi là giải pháp thay thế hiệu quả cho sấy phun trong công nghiệp. [@benelli_fluidized_2019; @souza_drying_2012] Phần tiếp theo sẽ đề cập tới một số phương pháp phổ biến trong làm khô cao chiết. 

### 5.2.5 Sấy phun tạo cao khô dược liệu

**Khái niệm chung về sấy phun**

Sấy phun được sử dụng rộng rãi trong một số lĩnh vực công nghiệp, chẳng hạn như dược phẩm, hóa chất, gốm sứ, polyme, thuốc nhuộm và bột màu, phân bón, chất tẩy rửa, enzyme khi mục tiêu là tạo ra các sản phẩm dạng bột từ dạng lỏng. Các sản phẩm sấy phun phổ biến trong cuộc sống hàng ngày của chúng ta, chẳng hạn như sữa bột, súp khô và cà phê bột. Thành phầm là dạng hạt, dạng bột thô hoặc bột mịn và có thể được sản xuất trong dây truyền liên tục bằng cách làm khô dung dịch, nhũ tương hoặc huyền phù. Một lợi thế quan trọng của sấy phun là khả năng tạo ra một sản phẩm có các đặc tính hóa lý định sẵn (Ví dụ: độ ẩm, hoạt độ nước, độ ẩm, độ hòa tan, khả năng phân tán lại, kích thước bột, mật độ rõ ràng, tính lưu động và khả năng nén), bằng cách điều chỉnh thông số thiết bị và yếu tố đầu vào. [@parikh_handbook_2021] 

Về mặt khái niệm, sấy phun là một quy trình đơn giản bao gồm chia dòng dung dịch thành các giọt nhỏ (một hỗn hợp rắn-lỏng) phun vào dòng khí nóng, thúc đẩy sự bay hơi của dung môi và tạo ra sản phẩm khô. Thiết bị chia thành các giọt mịn này có thể là súng phun ly tâm quay tốc độ cao, khí nén hoặc chất lỏng kép. Súng phun ly tâm quay tốc độ cao là thiết bị phổ biến nhất trong sản xuất công nghiệp trong khi máy sấy phun sử dụng khí nén lại phổ biến trong phòng thí nghiệm. Chiều dòng chất lỏng có thể cùng chiều, ngược chiều hoặc chiều hỗn hợp so với chiều khí nóng. Khí nóng sẽ mang theo sản phẩm sấy khô và khi khí thoát ra tạo ra dòng lốc xoáy để loại bỏ các bột sấy phun. Đồng thời, có thể các hạt thô sẽ xuất hiện ở đáy hình nón buồng sấy. [@parikh_handbook_2021; @masters_spray_1979] 

Hình 5.6 cho thấy sơ đồ của sấy phun. Sấy phun là quá trình truyền nhiệt và truyền khối đồng thời giữa khí nóng và giọt ướt. Cơ chế của sấy phun là sự khác biết về áp suất hơi của chất lỏng trên bề mặt giọt và áp suất riêng phần của chính nó trong dòng khí nóng. Nhiệt độ khí giảm nhanh chóng trong suốt quá trình hạt bay trong buồng sấy phun do sự truyền nhiệt ẩn cần thiết cho sự bay hơi của chất lỏng (làm mát bằng chính hơi nước bốc hơi). Bề mặt của giọt quá bão hòa trong chất lỏng và giữ cho giọt ở nhiệt độ thấp, dĩ nhiên, cho phép làm khô các hoạt chất nhạy với nhiệt. [@santos_spray_2018; @vehring_particle_2007] Quá trình khô sẽ diễn ra từ bề mặt của chúng vào bên trong và tạo ra lớp rắn bao bên ngoài được hình thành. Quá trình này cũng làm tăng mạnh độ nhớt trên bề mặt các giọt khiến chúng bị thủy tinh hóa (trạng hóa thủy tinh) trước khi xảy ra va chạm giữa chúng với thành buồng. Khi đó, độ dính chúng trên thành buồng sấy phun giảm cho phép chúng chảy tự do. Để sấy phun thành công, nhiệt độ và hàm lượng nước của các hạt phải hỗ trợ quá trình thủy tinh rắn. [@roos_importance_2002; @onwulata_encapsulated_2005] 

Ngoài các biến đổi vật lý, các biến đổi hóa học, sinh học và enzym khác cũng có thể xảy ra trong quá trình sấy phun. Điều này phụ thuộc vào đặc tính của sản phẩm được làm khô và các điều kiện xử lý. Một số biến đổi được mong muốn nếu chúng giúp nâng cao các đặc tính của sản phẩm, chẳng hạn như tăng khả năng hòa tan của sản phẩm và giảm lượng vi sinh vật (do đun nóng). Các biến đổi không mong muốn cũng có thể diễn ra, chẳng hạn như giảm hàm lượng các hoạt chất mục tiêu và suy giảm các hợp chất dễ bay hơi. 

Chất lượng của sản phẩm có mối liên hệ chặt chẽ với nguyên liệu đầu vào và các tham số trong quá trình vận hành. [@santos_spray_2018] Chất lượng của bột sấy phun có thể xem xét như khả năng trơn chảy, sức căng bề mặt, và tá dược thêm vào. [@kemp_drying_2017] Các yếu tố chính của quá trình vận hành gồm nhiệt đô, độ ẩm của khí sấy đầu vào, nhiệt độ của khí ở đầu ra, tốc độ sấy phun và áp suất đầu phun, tốc độ cấp nguyên liệu sấy phun. [@baumann_engineering_2021] Do đó, tối ưu hóa và kiểm soát quy trình giúp sản phẩm thu được có đặc tính hóa lý mong muốn kết hợp với năng suất sấy phun. 

**Sấy phun với cao dược liệu**

Sấy phun tạo cao khô dược liệu được sử dụng nhiều nhất trong quá trình loại dung môi từ bước chiết dược liệu. Sau quá trình sấy khô, hàm lượng của các hoạt chất sinh học và tính ổn định là hết sức quan trọng. [@baumann_engineering_2021] Mỗi nhóm hoạt chất sẽ có đặc tính hóa học riêng, do đó, không có quy trình chuẩn chung cho vận hành thiết bị. Đặc điểm kỹ thuật của quy trình phải dựa trên nghiên cứu thực nghiệm bao gồm trong đó cả đặc tính mong muốn của sản phẩm. Vi vậy các tính chất vật lý và hóa học của sản phẩm (ví dụ: hiệu suất, hàm lượng hoạt chất, phân bố kích thước hạt, hình dạng, nhiễu xạ tia X) và các thông số của thiết bị (ví dụ: năng suất sấy, sản xuất bột, hiệu quả sử dụng nhiệt, tiêu thụ năng lượng) cần được theo đánh giá trong quá trình phát triển sản phẩm. Ngoài ra cũng cần quan tâm đến xử lý sự cố trong quá trình sấy phun. Hiện tượng dính thường được mô tả gây giảm hiệu suất lẫn khó chịu trong vệ sinh thiết bị. Vấn đề này xảy ra thường xuyên khi dung dịch sấy phun giàu đường, đặc biệt, cao chiết thực vật lại chứa lượng đường khử, đường không khử, nhóm carbohydrate và acid hưu cơ cao hơn. [@padukka_evaluation_2000; @chu_impact_2000] Do đó, gần như bắt buộc phải thêm tá dược làm khô vào dung dịch chiết trước khi sấy phun để cải thiện chất lượng của bột sấy phun và hiệu năng của hệ thống.

**Tá dược dành cho sấy phun**

Lựa chọn chính xác tá dược dành cho sây phun là bước cơ bản để tạo ra bột sấy phun chất lượng, ổn định, có tác dụng sinh học. Tá dược lựa chọn được yêu cầu không gây tổn hại đến tác dụng sinh học cao chiết từ thực vật, trơ về mặt hóa học và ổn định dưới tác động của nhiệt. [@cortes-rojas_physicochemical_2012] Polyme, polysacaride và gôm là những tá dược phổ biến dành cho sấy phun. Một số tá dược sử dụng để tạo lớp màng bảo vệ các hoạt chất hoặc thúc đẩy quá trình giải phóng hoạt chất có kiểm soát. [@kemp_drying_2017]  Tá dược có thể sử dụng đơn độc hoặc phối trộn với tỷ lệ thích hợp. Tỷ lệ này dựa trên từng tình huống cụ thể phụ thuộc vào thành phần trong dung dịch chất xuất. [@kemp_drying_2017] Tá dược cũng cần có chức năng giúp tăng nhiệt độ chuyển hóa thủy tinh trong quá trình sấy khô, do đó, thúc đẩy giảm độ dính của sản phẩm trong quá trình sấy và bảo quan. Sản phẩm có độ ổn định cao hơn. [@roos_importance_2002; @onwulata_encapsulated_2005; @muzaffar_stickiness_2015] Ví dụ về các tá dược được sử dụng rộng rãi trong quá trình sấy phun cao dược liệu gồm silicon dioxide dạng keo (SiO2; CAS: 7631-86-9), Maltodextrins ([C6H10O5] nH2O) của các chất tương đương dextrose khác nhau, gôm Arabic (còn được gọi là gôm acacia), cyclodextrin (CD) và dẫn xuất CD (ví dụ: $alpha$-CD, $beta$-CD, $gamma$-CD, dimethyl-$beta$-CD, 2-hydroxyethyl-$beta$-CD, trimethyl-$beta$-CD), tinh bột và tinh bột biến tính, và cellulose vi tinh thể (MCC). Thông tin liên quan đến các đặc điểm và tính chất chính của những tá dược này có thể được tìm thấy trong Sheskey *et al.* [@sheskey_handbook_2020]


### 5.2.6 Đông khô áp dụng dịch chiết từ dược liệu

**Khái niệm chung về đông khô**

Đông khô là quá trình diễn ra tại điều kiện cụ thể bên dưới điểm ba của một chất, tại điều kiện này nước chuyển trực tiếp tự pha rắn sang pha khí (sự thăng hóa). Điểm này có thể xác định dựa trên giản đồ pha áp suất- nhiệt độ. Điểm ba là điểm mà vật chất tồn tại cùng trạng thái rắn, lỏng và khí. Với nước, điểm ba xảy ra tại nhiệt độ 273,16 K (0,01 $^o$C) và áp suất 610,62 Pa (4,58 torr). Quy trình thực hiện như sau gồm đông lạnh mẫu hóa rắn ở nhiệt độ thấp, sau đó, giảm áp suất tới mức rất thấp làm hơi nước thăng hóa. 

Quá trình loại bỏ nước trong đông khô trải qua 3 bước sau. Bước đầu tiên là đóng băng vật liệu. Đây là bước quyết định đối với chất lượng của sản phẩm đông khô vì tốc độ đóng băng quyết định phân bố và kích thước lỗ xuất hiện và kết cấu của khối rắn. Tiếp theo là sấy sơ cấp xảy ra nhiệt độ thấp trong chân không. Bước này liên quan đến loại nước bằng thăng hoa. Cuối cùng là sấy thứ cấp hoặc giải hấp phụ khi độ ẩm được loại bỏ bằng cách loại bỏ nước liên kết với cấu trúc vật liệu. Quá trình này diễn ra ở nhiệt độ cao hơn để tăng tốc độ. [@hua_freeze-drying_2010] Toàn bộ quy trình diễn ra tại nhiệt độ thấp giúp phương pháp này phù hợp với các chất dễ biến đổi như bị protein, hoạt chất dễ bị thủy phân hay oxy hóa đồng thời cũng giảm thiểu sự bay hơi của chất dễ bay hơi. [@kemp_drying_2017] Loại nước bằng phương pháp này diễn ra chậm, và có thể giảm thời gian bằng cách giảm áp suất nhưng cũng chỉ ở giới hạn nhất định. Thêm nữa, nhiệt độ buồng sấy phải thấp hơn ít nhất là 15-20 $^oC$ khi so với nhiệt độ đóng băng của dung mội. [@ofagain_lyophilization_2003] Từ đó, quá trình đông khô đòi hỏi chi phí cao do thời gian dài, vận hành và bảo trì thiết bị. Bù lại, chất lượng sản phẩm đông khô thường cao hơn. Một số sản phẩm sử dụng phương pháp đông khô trong lĩnh vực dược như enzyme, protein, thuốc kháng sinh, vaccin và huyết thanh. Với lĩnh vực dược liệu, một số sản phẩm chất lượng cao áp dụng phương pháp này như cà phê, trà, siro cây phong. [@pudziuvelyte_freeze-drying_2020; @bhatta_freeze-drying_2020] 

**Đông khô với cao dược liệu**

Đông khô phổ biến trong nghiên cứu và phát triển nhưng đã có một số sản phẩm đã được thương mại hóa trên thị trường. Abascal *et al.* đã đánh giá về tác động của đông khô và ý nghĩa đối với chất lượng cao chiết từ dược liệu. [@abascal_effect_2005] Nhóm tác giả thấy rằng đông khô gây ra tác động không lượng trước và có thể tác động đáng kể tới thành phần các hợp chất tự nhiên trong cao chiết như thay đổi hàm lượng phenolic, carotenoid và các chất dễ bay hơi. Tác giả đề xuất phải có các nghiên cứu chi tiết từ tính chất của dịch chiết ban đầu gồm hàm lượng, nồng độ để xác định thông số quá trình đông khô giảm thiểu sự thay đổi hoạt chất và chất lượng cũng như thời hạn sử dụng của sản phẩm. Các tá dược thêm vào cũng ảnh hưởng nhất định đến chất lượng sản phẩm. Nghiên cứu quá trình đông khô trên cao chiết cồn của loài *Elsholtzia ciliata*. Pudziuvelyte *et al.* nhận thấy các tá dược natri caseinat, gôm Arabic, maltodextrin, $beta$-maltodextrin và maltodextrin khan đơn độc cho sản phẩm kém hơn nếu sử dụng hỗn hợp kết hợp theo từng cặp tá dược (tổng nồng độ không quá 20%w/w trong sản phẩm cuối). Sản phẩm sẽ cho độ hòa tan tốt hơn, chỉ số trơn chảy Carr và tỷ lệ Hausner cao hơn trong khi sản phẩm khô hơn (độ ẩm thấp hơn). Tá dược đơn độc maltodextrin cho sản phẩm kém nhất trong khi nếu natri caseinat lại cao nhất. [@pudziuvelyte_freeze-drying_2020] 

So sánh về công nghệ sấy khô giữa sấy tầng sôi, sấy phun và đông khô cũng đã được nghiên cứu. [@pop_application_2013] Đối tượng nghiên cứu là dung dịch nước chiết từ lá cây óc chó ba tư (*Juglans regia*), cây tầm gửi châu Âu (*Viscum album*) và vỏ cây liễu trắng (*Salix alba*) thu được bằng cách chiết ngâm 48 giờ với acid HCl 1%, nồng độ dung dịch luôn duy trì 15% rắn/lỏng. Tá dược sử dụng là maltodextrin, lactose và NaCl với tỷ lệ rắn/dịch chiết là 10:90. Áp dụng ba phương pháp sấy khô vừa đề cập, cụ thể sấy phun với nhiệt độ vào 190 $^o$C, Nhiệt độ ra = 45$^oC$; sấy tầng sôi: Nhiệt độ vào = 80 $^oC$, nhiệt độ ra = 40 $^oC$; đông khô: -55 $^oC$, 0,12 mbar trong 7 giờ sấy sơ bộ và -5 $^oC$; 0,12 mbar trong 3 giờ-sấy khô lần cuối. Kết quả cho thấy tính chất vật lý và hóa học của cao chiết khô bị ảnh hưởng bởi phương pháp và tá dược sử dụng. Ví dụ, sản phẩm tốt nhất thu được từ sấy phun và đông khô với cao chiết từ cây liễu trắng và tá dược sử dụng là lactose. Tổng hàm lượng polyphenol trong bột lá cây óc chó ba tư cao nhất với phương pháp đông khô sử dụng tá dược NaCl hoặc lactose. Trong khi đó, tổng hàm lượng polyphenol cao nhất sử dụng sấy phun với dịch chiết từ cây tầm gửi (82%). Từ đó có thể tạm kết luận rằng chất lượng sản phẩm của cao chiết từ thực vật phụ thuộc vào phương pháp sấy cũng như tá dược sử dụng. 

**Tá dược sử dụng với đông khô**

Quá trình này thường thêm một số tá dược, chất bảo quản hoặc điều hương và dịch chiết trước khi đông khô để cải thiện chất lượng sản phẩm. Phân loại tá dược thêm vào như dựa trên trọng lượng phân tử hoặc chức năng trong chế phẩm như chống oxy hóa, tạo hệ đệm, tạo hình dạng cho thành phẩm. Saccharide (lactose, maltose, trehalose, sucrose), polysacaride (cellulose, dextran), polyol (mannitol, sorbitol, xylitol), acid amin (glycine, histidine và arginine), chất diện hoạt và một số loại muối là phụ gia phổ biến trong đông khô. [@bjelosevic_excipients_2020]


### 5.2.7 Kiểm tra độ ổn định của dược liệu khô và cao khô

Đánh giá độ ổn định của sản phẩm là bước cuối cùng trong phá triển sản phẩm trước khi đưa ra ngoài thị trường. Việc đánh giá này đảm bảo tính an toàn, hiệu quả và duy trì chất lượng trong quá trình lưu hành trước khi hết hạn sử dụng. Thử nghiệm độ ổn định được tiến hành ở điều kiện bảo quản thiết lập trước dựa trên loại thử nghiệm, vùng khí hậu [@bott_storage_2007], dạng bào chế và đóng gói sản phẩm cuối trước khi lưu hành. Các yêu cầu tối thiểu trong thử nghiệm ổn định phải được thực hiện theo yêu cầu của Cục Quản lý Dược Việt Nam. Hầu hết các yêu cầu này được hài hòa giữa các quốc gia và theo khuyến nghị đề xuất bởi Hội nghị quốc tế về hài hòa (International Conference on Harmonisation) [@rignall_ichq1a_2017] và của WHO. [@who_annex_2021] 



Các sản phẩm có nguồn gốc từ thảo dược bao gồm cả cao khô dược liệu dễ bị biến đổi do thay đổi bởi nhiệt độ bảo quản, thời gian, độ ẩm, cường độ ánh sáng. Do đó, thử nghiệm độ ổn định với hoạt chất chính hoặc sản phẩm là bắt buộc để đảm bảo chất lượng. Sự thay đổi màu sắc, khả năng hút ẩm, kích thước hạt, hình thái, độ trơn chảy, trạng thái kết tính, độ hòa tan, khả năng tái phân tán trong nước, độ ẩm, hàm lượng hoạt chất đánh dấu, sự xuất hiện kim loại nặng và các xét nghiệm vi sinh là các yêu cầu cần theo dõi định kỳ trong quá trình nghiên cứu độ ổn định. 

Từ nghiên cứu có thể đề xuất hạn sử dụng cho sản phẩm. Tuy nhiên, đánh giá độ ổn định các chế phẩm từ thảo dược phức tạp hơn. Nếu chỉ dựa trên đánh giá sự thay đổi của hoạt chất đánh dấu thì kết quả cuối có thể chưa như kỳ vọng. Trong hầu hết các nghiên cứu, các hoạt chất đánh dấu sẽ thay đổi nồng độ. Ngoài ra, tác dụng của cao chiết có thể do hàng chục chất hiệp động tác dụng. Sự xuất hiện các chất mới đôi khi gây độc có thể xảy ra trong quá trình nghiên cứu độ ổn định. Việc xuất hiện các hợp chất này có thể do quá trình thủy phân, khử hydro, epoxy hóa hoặc đứt liên kết đôi hoặc do enzyem gây ra. Đôi khi chúng diễn ra mà các phương pháp phân tích hóa lý không phát hiện ra được. [@lund_control_2017] 

Các hướng dẫn nghiên cứu độ ổn định thường lựa chọn phương pháp lão hóa cấp tốc với nhiệt độ và độ ẩm cao dẫn tới tác động không mong muốn trên các sản phẩm từ tự nhiên. Sự thay đổi về trạng thái vật lý, màu sắc, độ trơn chảy, độ hòa tan, khả năng phân tán và đóng bánh sản phẩm là các vấn đề thường xuyên gặp trong nghiên cứu độ ổn định. Sự đóng bánh do bề mặt hạt bị thấm ướt gây ra tính dẻo và đôi khi hòa tan các hoạt chất sau đó là kết tụ tức thời, thường chúng xảy ra với bột vô định hình. Với các khó khăn này, nghiên cứu độ ổn định trên cao chiết từ dược liệu hoặc sản phẩm từ dược liệu là một quá trình phúc tạp, khó khăn và tốn kém. Đấy chưa kể xét tới khía cạnh tác dụng sinh học mới là yếu tố then chốt của sản phẩm từ thảo dược. Một số nghiên cứu độ ổn định kèm theo nghiên cứu sự thay đổi tác dụng sinh học vì trong cao chiết thường đa thành phần và sự biến đổi không lường trước trong quá trình nghiên cứu độ ổn định. [@thamkaew_review_2021; @azmir_techniques_2013]


### 5.3 Tổng kết

Công nghiệp dược liệu có thể hiểu là sử dụng khoa học và kỹ thuật để sản xuất các sản phẩm mới có hoạt tính sinh học từ thực vật. Các sản phẩm này có thể ứng dụng trong một số lĩnh vực bao gồm dược phẩm, mỹ phẩm, thực phẩm, hóa chất, thú ý và công-nông nghiệp. Các ứng dụng đáng chú ý của thảo mộc bao gồm sản xuất cao được tiêu chuẩn hóa, dược phẩm, tinh dầu, nước hoa và thuốc trừ sâu. Nhu cầu về các sản phẩm này là rất lớn và ngày càng gia tăng. Điều này đòi hỏi cao hơn về yêu cầu giám sát chất lượng. Tuy nhiên, công nghiệp dược liệu do đa ngành cùng tham gia cũng như kiến thức từ nhiều lĩnh vực đóng góp. Hoàn thiện quy trình và tối ưu hóa chất lượng là những yêu cầu chính trong việc phát triển sản phẩm từ dược liệu để nâng cao giá trị cho cây thảo dược. Khâu trồng trọt và thu hái dược liệu, xử lý sơ cấp, xử lý sơ bộ mặc dù chưa được đề cập nhưng đây là yếu tố quan trọng đảm bảo chất lượng sản phẩm. Chương này đã đề cập tới làm khô dược liệu cũng như kỹ thuật sấy khô để tạo cao chuẩn hóa. Tất cả các công đoạn vừa đề cập đều hướng tới sản xuất bền vững thân thiện với môi trường từ chuỗi cung ứng nguyên liệu thảo dược tươi đến ra sản phẩm bán trên thị trường. Dược liệu hiện tại ngoài các hoạt động phát triển thuốc mới, việc sử dụng hiệu quả nguồn nguyên liệu trong sản xuất không chỉ là yêu cầu của cơ quản quán lý mà còn của người tiêu dùng. 


# Bibliography {-}