---
title: "Sách: Tài liệu các kỹ thuật chiết suất các hợp chất từ tự nhiên"
author: "TS. Hoàng Lê Sơn"
format: 
    html: 
        toc: true
        toc-depth: 3
        lightbox: true
---

## Lời giới thiệu

## Danh mục các thuật ngữ {#danh-mục-các-thuật-ngữ .unnumbered}

  **STT**   **Viết tắt**   **Tiếng Anh**                         **Tiếng Việt**
  --------- -------------- ------------------------------------- ------------------------------------
  01                       Soxhlet extraction                    Chiết Soxhlet
  02                       Maceration                            Chiết ngâm
  03                       Hydrodistillation                     Cất kéo hơi nước
  04        PLE            Pressurized Liquid Extraction         Chiết lỏng dưới áp suất
  05        MAE            Microwave-assisted Extraction         Chiết xuất làm nóng bằng sóng viba
  06                       Enzyme-assisted Extraction            Chiết sử dụng enzyem
  07        SFE            Supercritical Fluid Extraction        Chiết xuất siêu tới hạn
  08        UAE            Ultrasound-assisted Extraction        Chiết xuất hỗ trợ bởi sóng siêu âm
  09        PEF            Pulse Electric Eield Extraction       Chiết xuất sử dụng dòng điện
  10        CLLE           Continuous Liquid-Liquid Extraction   Chiết lỏng lỏng liên tục

## Tóm tắt các chương
### Phần 1: Đại cương về chiết suất
#### [Chương 1: Đại cương về cao chiết và hợp chất tự nhiên](../KyThuatChietXuat/part_1/chapter_1.qmd)

:::{.callout-note}
## Tóm tắt
Hoạt chất có hoạt tính sinh học có thể tìm thấy rộng rãi trong các thực vật và thường được xếp vào nhóm các hợp chất chuyển hóa bậc hai. Dựa trên cấu trúc hóa học, các hoạt chất này có thể thuộc một số nhóm flavonoide, tannin, terpene, ligand, alkaloid, peptide hoặc một số nhóm khác. Việc chiết suất được các hợp chất này ngày càng quan trọng trong công nghiệp dược do tiềm năng tác dụng sinh học của chúng như khả năng chống oxy hóa, kháng viêm để áp dụng trong các liệu pháp điều trị như ngăn ngừa các rối loạn tim mạch hoặc ức chế phát triển tế bào ung thư. Mặc dù, các kỹ thuật sắc ký kết hợp với phân tích các loại phổ như khối phổ, phổ hồng ngoại-tử ngoại và phổ cộng hưởng tử hạt nhân có thể đóng vai trò đáng kể trong phát hiện các hợp chất này nhưng một dự án phát triển sản phẩm từ tự nhiên thành công phần lớn phụ thuộc vào phương pháp chiết xuất để có thể thu được cao chiết giàu. Sản phẩm của quá trình chiết xuất có thể tiếp tục để làm giàu hoặc phân lập các hợp chất đích hoặc cũng có thể đạt chất lượng để bào chế thành phẩm. Do đó, chương này sẽ đề cập tới các nhóm hoạt chất có tác dụng sinh học và vai trò cao chiết từ thực vật trong lĩnh vực Dược - Mỹ phẩm.
:::

### [Chương 2: Phương pháp chiết suất thường quy](../KyThuatChietXuat/part_1/chapter_2.qmd)

:::{.callout-note}
## Tóm tắt
Cao chiết từ thực vật có thể được chiết xuất bằng nhiều phương pháp khác nhau. Theo cách phân loại hiện tại, các phương pháp này chia thành hai nhóm gồm các phương pháp thường quy và các phương pháp mới. Chương này đề cập tới các phương pháp thường quy trong chiết xuất gồm chiết Shoxlet, chiết ngâm, cất kéo hơi nước. Các phương pháp này sử dụng dung môi hữu cơ hoặc nước tại áp suất khí quyển. Dung môi được lựa chọn hướng tới thu được nhóm hoạt chất mong muốn cao nhất và ít tạp chất. Nguyên tắc chung là dung môi phân cực có thể chiết được nhóm hợp chất phân cực trong khi dung môi không phân cực có thể chọn được nhóm không phân cực. Tuy nhiên trong thực tế phức tạp hơn do đa dạng thành phần trong dược liệu với tương tác giữa nhiều yếu tố khác nhau. Dung môi trong phương pháp chiết Shoxlet có thể là nước hoặc dung môi hữu cơ trong khi cất kéo hơi nước chỉ dùng nước làm dung môi. Chương này sẽ cung cấp khái niệm cũng như ưu nhược điểm từng phương pháp vừa đề cập.
:::

### [Chương 3: Các phương pháp chiết suất mới](../KyThuatChietXuat/part_1/chapter_3.qmd)

:::{.callout-note}
## Tóm tắt
Các phương pháp chiết xuất thông thường đang dần được thay thế bằng các phương pháp mới do một số nhược điểm như chí phí cao, thời gian chiết xuất dài, ảnh hưởng tới các hợp chất không bền với nhiệt, độ chọn lọc thấp, dung môi cần tinh khiết. Các phương pháp chiết xuất mới được phát triển hơn 50 năm qua hứa hẹn khác phục các vấn đề của phương pháp truyền thống. Một số nhược điểm đã được cải thiện như thời gian chiết xuất ngắn hơn, chất lượng đồng nhất, hiệu suất cao hơn. Đặc biệt, dung môi hữu cơ và tổng hợp sử dụng ít hơn. Các phương pháp chiết mới của hợp chất tự nhiên được đề xuất trong tài liệu này gồm siêu âm, gia nhiệt, chiết bằng gia nhiệt bằng điện trở, gia nhiệt bằng vi sóng, điện trường xung, chiết suất có sự hỗ trợ bằng áp suất, chất lỏng siêu tới hạn, và hộ trợ chiết bằng enzym. Đích tới của các phương pháp này thường sẽ hướng tới giảm thiểu ô nhiễm môi trường và tốn phí năng lượng trong tổng quá trình thấp.
:::
## Phần 2: Các chuyên đề nâng cao

### [Chương 4: Dung môi trong chiết suất](../KyThuatChietXuat/part_2/chapter_4.qmd)

:::{.callout-note}
## Tóm tắt
Dung môi rất cần thiết trong việc chiết xuất các hợp chất từ tự nhiên. Chiết xuất Soxhlet, chiết ngâm và lắc phân đoạn lỏng-lỏng là các ví dụ về sử dụng dung môi để thu được hoạt chất từ các mô thực vật. Sử dụng các phương pháp chiết xuất xanh như vi sóng, siêu âm giúp giảm lượng dung môi sử dụng, giảm thời gian chiết xuất và nâng cao hiệu quả chiết xuất. Các phương pháp này đều đỏi hỏi sử dụng dung môi để hòa tan hoạt chất, tách ra khỏi tế bào thực vật. Sự đa dạng của thành phần hóa học trong thảo dược cũng như phức tạp về tính chất hóa lý do tương tác giữa các thành phần dẫn đến khó khăn lựa chọn dung môi. Mong muốn một dung môi hiệu quả trong quá trình chiết xuất nhất định cần quan tâm tới các đặc tính như tính phân cực, khả năng truyền nhiệt, khả năng hòa tan, độc tính và các thông số hóa lý, bao gồm nhiệt độ sôi, độ nhớt và mật độ phân tử. Chương này đề cập tới các loại dung môi đang được nghiên cứu phát triển ứng dụng trong quá trình chiết suất.
:::

### [Chương 5: Kỹ thuật làm khô](../KyThuatChietXuat/part_2/chapter_5.qmd)

:::{.callout-note}
## Tóm tắt
Quy trình sản xuất cao chiết từ dược liệu thường gồm các công đoạn nhỏ gồm xử lý dược liệu tươi, chiết thu dung dịch và làm cô đặc cao dược liệu. Với sản xuất tinh dầu bằng cất kéo hơi nước quá trình chiết và thu tinh dầu trong cùng một thiết bị nhưng quá trình xử lý dược liệu có thể ảnh hưởng đến chất lượng sản phẩm.
:::

### [Chương 6: Một số quy trình chiết suất](../KyThuatChietXuat/part_2/chapter_6.qmd)

:::{.callout-note}
## Tóm tắt
Chương này đề cập tới một số quy trình chiết suất các hợp chất từ tự nhiên.
:::

